### ISSUE TITLE
Why use `resolve` for link?

### ISSUE THREAD

**Issue by muhajirframe** [saltyshiomix/nextron#10]
I notice that for link we use `href={resolve('pathname')}`. Why so? We could just use `next/link` isn't it?

**Comment by saltyshiomix** [comment]
Hi, @muhajirframe , sorry for replying so late.

When production build, electron can handle only static files.
So you can't use absolute link like `/pathname`, and nextron resolves path according to build mode :)

As of `nextron@3`, you'll see a `resolve` helper in `renderer/helpers/resolve.{js|ts}`.

```js
module.exports = function resolve(pathname) {
  if (process.env.NODE_ENV === 'production') {
    if (/\.(png|jpe?g|gif|svg|js|css)(\?.*)?$/.test(pathname)) {
      return `../${pathname}`
    }
    return `../${pathname}/index.html`
  }
  return '/' + pathname
}
```
