### ISSUE TITLE
Nextron build api-routes examples does not work

### ISSUE THREAD

**Issue by andregr15** [saltyshiomix/nextron#101]
#### Issue description
Good afternoon.

The build version of api-routes examples does not work, the application can't access the route app://.//api/people.

#### Steps to reproduce the issue

1. npx create-nextron-app api-routes --example api-routes 
2. cd api-routes 
3. yarn or npm install
4. yarn build or npm run build
5. execute the dist unpacked file ( on linux - my-nextron-app)

#### What's the expected result?

- The application should load and fetch data from the api

#### What's the actual result?

- The application can't load and fetch the data

#### Additional details / screenshot

![image](https://user-images.githubusercontent.com/17393251/92957094-6356bd00-f43e-11ea-9e42-901c3e592603.png)

`on development works fine`

![image](https://user-images.githubusercontent.com/17393251/92957252-a022b400-f43e-11ea-926c-ccd7413ae2b4.png)

**Comment by saltyshiomix** [comment]
@andregr15 

Thank you for your reporting the issue!

As mentioned in the [README](https://github.com/saltyshiomix/nextron/blob/master/examples/api-routes/README.md), `api-routes` example works only development mode :)
