### ISSUE TITLE
I cannot upload images in production

### ISSUE THREAD

**Issue by AhmedGamal1496** [saltyshiomix/nextron#103]
When building my electron app, everything is fine except it cannot upload any files. 
It keeps throwing this error: `Failed to load resource: net::ERR_FILE_NOT_FOUND`

May you help me, please?

**Comment by saltyshiomix** [comment]
@AhmedGamal1496 

Where is your uploading files?
You can't upload inside the electron app, so we have to upload in the user directory.

**Comment by AhmedGamal1496** [comment]
My files directory to be uploaded are something like this: `/home/jimy/Pictures/162938.png`

**Comment by AhmedGamal1496** [comment]
![Screenshot from 2020-09-28 17-34-40](https://user-images.githubusercontent.com/43505332/94453437-f3bc2e00-01b0-11eb-99a3-e74ad08a8684.png)

Here you can see the file details. It always has a status of error, but I think it grabs the path correctly. This happens only in the production environment. 

I am using the upload component of ant design library.

**Comment by saltyshiomix** [comment]
Ok, I think your investigation is correct.

It may be the cause of `electron-serve` bacause which registers the file protocol like `app://./home.html`.

And `input type="file"` holds the file in the local page (like `home.html`), but when uploading it we need to get the full path.

Could you `console.log()` the file path which produces that error? Or is it impossible? (If impossible, nextron needs to be changed drastically. It may take a long time to fix this problem.)

**Comment by saltyshiomix** [comment]
@AhmedGamal1496 

Ok, I think your investigation is correct.

It may be the cause of `electron-serve` bacause which registers the file protocol like `app://./home.html`.

And `input type="file"` holds the file in the local page (like `home.html`), but when uploading it we need to get the full path.

Could you `console.log()` the file path which produces that error? Or is it impossible? (If impossible, nextron needs to be changed drastically. It may take a long time to fix this problem.)

**Comment by saltyshiomix** [comment]
@AhmedGamal1496 

I finally got it this is the security issue only appearing when production build.

We can't access files unless we use electron [dialog](https://github.com/electron/electron/blob/master/docs/api/dialog.md) (main process).

So I think you can't use the upload component directory.

**Comment by AhmedGamal1496** [comment]
@saltyshiomix 
Hello sir, I was able to solve my problem. as you said the Upload component tries to post a request to a server `app://...`, but what I actually interested in is only the old&new paths and the data of the image, so I had to configure and play around the Upload component to read the data of the image myself. 

What I have found to prevent the component from sending a POST request is to return false after finishing all my operations in the beforeUpload prop of the Upload component of antd so as to prevent it from sending a POST request to a remote server. 

I hope I clarified the solution correctly. Everything is fine until now, I will let you know if I encountered any issues in the production environment.

**Comment by saltyshiomix** [comment]
@AhmedGamal1496 
I think you clarified the solution correctly.
(Please forgive me if I misunderstand your comments because of my poor English skills. Sorry in advance.)

If any troubles, feel free to ask me :)

I hope your success in the production!
