### ISSUE TITLE
example using webContents.send

### ISSUE THREAD

**Issue by paragbaxi** [saltyshiomix/nextron#104]
I'm unable to produce a simple ipc communication from main to renderer using webContents.send(). 

I get the following error:
`TypeError: ipcRenderer.on is not a function`

**Comment by saltyshiomix** [comment]
@paragbaxi 

Have you checked the next's webpack process is the server or the client one?

See the tips in the [README](https://github.com/saltyshiomix/nextron#tips).

And ipc communication example is [here](https://github.com/saltyshiomix/nextron/tree/master/examples/ipc-communication).

If you have any other troubles, feel free to issue me up :)

**Comment by paragbaxi** [comment]
Will check it out and report back! 

I already reviewed the IPC example but that only shows renderer to main, not main to renderer.

**Comment by saltyshiomix** [comment]
Ok, I hope it helped :)

Note: `ipcMain` exists only in main process, and `ipcRenderer` exists only in client (renderer) process.

**Comment by paragbaxi** [comment]
It did!

Working code:
```
const ipcRenderer = electron.ipcRenderer || false;
if (ipcRenderer) {
  ipcRenderer.on('checkValues:update', (event, results) => {
    console.log(results);
  });
}

```

**Comment by saltyshiomix** [comment]
@paragbaxi 

Congrads!
