### ISSUE TITLE
const store = new Store({ name });

### ISSUE THREAD

**Issue by paragbaxi** [saltyshiomix/nextron#106]
This expression is not constructable.
  Type 'typeof ElectronStore' has no construct signatures.ts(2351)
create-window.ts(6, 1): Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.

**Comment by saltyshiomix** [comment]
@paragbaxi 

Ok, I'll consider it until next major release!

**Comment by b3nab** [comment]
I don't think electron-store should be used in renderer process. I'm currently using nextron with electron-store (on the main process only) and it works fine. 

What are you trying to do?
Maybe you can solve with the IPC (inter process communication) module of electron to let communicate main and renderer process.

**Comment by paragbaxi** [comment]
ended up bypassing, don't remember how.

fyi, you can use electron-store in either
> You can use this module directly in both the main and renderer process.
