### ISSUE TITLE
Couldn't build example

### ISSUE THREAD

**Issue by theNewJson** [saltyshiomix/nextron#11]
I am working on a project with Next and Electron so this project really helped me a lot.
Thank you for your effort so far.
Everything works fine on dev.
However, I encountered an error when I tried to build the basic code(the files you get after init):
<img width="951" alt="2018-10-02 4 09 26" src="https://user-images.githubusercontent.com/37173252/46336827-7790bd80-c65e-11e8-9c8c-35e553d02734.png">
I know that this is probably not an issue of nextron, but I've been stuck for days trying to build my project.
Any suggestions maybe?
Thank you.

**Comment by saltyshiomix** [comment]
Hi @theNewJson , thank you for your reporting a bug of nextron 👍 

Could you tell me what the version of nextron?

```bash
$ nextron --version
```

Also, if you have some time, could you tell me a result after running these commands?

```bash
# run this build command and make sure you got the error above you know
$ yarn build

# I want to know console outputs after run this command
$ npx electron-builder
```

**Comment by saltyshiomix** [comment]
`nextron` internally uses an `electron-builder` command when you run `npm run build`.

Your console output shows "success" until "Building main process", so nextron fails when packaging by `electron-builder`.

I tried `nextron@2.0.4` on my Windows 10 and Mac, but the command `npm run build(yarn build)` won't show your error outputs ;(

**Comment by saltyshiomix** [comment]
`npm ls --prod` shows missing dependencies, and nextron internally has `ts-loader` so `typescript` is missing dependencies in JavaScript examples.

In `electron-builder`, env `ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true` can ignore these missing dependencies.

**Comment by saltyshiomix** [comment]
Fix this bug as of `nextron@2.0.5` 👍 

```bash
# install latest nextron
$ npm install --global nextron@latest

# basic one
$ nextron init test-app
$ cd test-app
$ yarn
$ yarn build

# when use examples/with-javascript-material-ui
$ nextron init test-app --template with-javascript-material-ui
$ cd test-app
$ yarn
$ yarn build
```

**Comment by theNewJson** [comment]
Wasn't expecting such a fast reply :satisfied:

Just want to let you know....
![image](https://user-images.githubusercontent.com/37173252/46386497-5ed2e700-c6f4-11e8-9b79-c9423314b9d2.png)
Everything works perfectly!!! 👍

I will keep on working the project and I will let you know if I have any more questions about nextron.
Again, thank you for your effort! :clap:

**Comment by theNewJson** [comment]
So I added more files to my project especially some server files so that I can build a simple express server and connect to my database.
Now the file structure looks like this:
```
my-app
  |__renderer
  |__server
  ...
  |_background.js
```
the express server is required and run in the background.js file.
Again, works great on dev and fails at production.
No errors shown during build.
But when I try to open the file:
![image](https://user-images.githubusercontent.com/37173252/46397297-6d38f700-c724-11e8-90da-c61768be3f26.png)

I was completely new to electron and not a master of Next.js so I might have made some simple mistakes here.
Is there a predetermined file structure?
Thank you.

**Comment by saltyshiomix** [comment]
@theNewJson , I'm glad to hear that ❤️ 
Please contact me if any questions!
Thanks,

**Comment by DanielDoe** [comment]
Hello please I think i've got the same issue
![nextron](https://user-images.githubusercontent.com/30290716/57570303-52380f00-73f8-11e9-934a-a74dff61832e.JPG)


upgraded to the latest nextron but still couldnt build and i am way done with my project... i should have built the template first #Crying

![npmbuild](https://user-images.githubusercontent.com/30290716/57570342-a6db8a00-73f8-11e9-842d-3c52af37465a.JPG)

tried with npm too
