### ISSUE TITLE
How do I loop through a local directory?

### ISSUE THREAD

**Issue by UmarAbdullahi** [saltyshiomix/nextron#118]
Hello, I get undefined error when I try to load local files using the code below: 

`const fs = require('fs')
fs.readdir("http://localhost:8888/images/", (err, files) => {
  console.log(files)
}) ` 

Please how do I loop through a directory?

**Comment by saltyshiomix** [comment]
Hi @UmarAbdullahi !

You can't loop from the URL because the URL is not a directory.

We must use the electron's main process via ipc-communication:

```js
// background.js
ipcMain.on('get-files', (event, arg) => {
  fs.readdir('/absolute-path/to/images', (err, files) => {
    event.sender.send('files', files);
  });
});
```

```js
// renderer process

// fire the event
ipcRenderer.send('get-files');

// receive the files
ipcRenderer.on('files', (event, data) => {
  console.log(data);
});
```

**Comment by UmarAbdullahi** [comment]
Thank you a lot
@saltyshiomix
