### ISSUE TITLE
What is the difference between setup and executable?

### ISSUE THREAD

**Issue by Psycokwet** [saltyshiomix/nextron#122]
I kind of think that the setup that we get after building, install the app in the computer, and not the executable, alright. But, why does it launch the app itself as well ? Can we detect from the executable if we have been called from the setup or the executable? To launch setting up code in the setup exec instead of launching the app for example?

Or we may as well use the executable and never use the setup?

I am on windows, and my app must work on mac too (couldn't test there until now)

**Comment by saltyshiomix** [comment]
@Psycokwet 
I think it is impossible to detect that, because both of them are the same executable. The difference is the place to be installed in.
