### ISSUE TITLE
Bug : Deleted icons still get into the build

### ISSUE THREAD

**Issue by Psycokwet** [saltyshiomix/nextron#123]
It's not a big issue, I think, but for some reasons, when I replaced the original icon with mine, this happened : 
- I add my icon into resources, as a icns and as a ico file
- I change the name of the original icon for icon-ex.ico and icon-ex.icns
- I put my new icon files as the right name
Since then, in every build I do, the "icon-ex" file is present as well as my icon file. No other image have been affected ince then. I tried to put other assets in the resources folder, but they don't seem to be "captured" into my build for some reasons?
Now I have tried to completely delete my "ex-icon" from the resource folder, I have deleted the dist folder as well, but, when I build, the "icon-ex" appear again in my dist. I haven't been able to duplicate the issue with another file, but I can't get rid of this ghost files in my build.

logo-ex.png does appear in my app folder, and deleting it does not have any effect on the next build. I don't know how do the build manage to get this file back whatever I do ._.

**Comment by saltyshiomix** [comment]
@Psycokwet 
This is not a nextron side, but a cache problem on your OS :)

Please investigate how to delete the cache from your computer.

**Comment by Psycokwet** [comment]
Oh thank you ! Sorry for thinking it was with Nextron, I didn't know there were such a thing honestly.

Even after cleaning the cache it's still there somehow, but I will investigate further another time, since it's not a big deal. :)

**Comment by saltyshiomix** [comment]
No problem :)

Yes that problem ocurred in my Windows environment, but I do understand this is a cache problem :)

One question, your deleted cache is placed where?

**Comment by saltyshiomix** [comment]
@Psycokwet 

👆(if you have time)

**Comment by Psycokwet** [comment]
I deleted every cache I could a part from my download folder and my past windows installation (I resetted my computer a few days ago), do you want the full list of kind of cached data I deleted ?
Or did I misunderstood the question? :o
