### ISSUE TITLE
Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by dillonco** [saltyshiomix/nextron#124]
I'm getting some strange errors on my project that I couldn't debug so I tried starting fresh.
I ran `npx create-nextron-app est2 --example with-javascript-material-ui`
and then `npm install && npm run dev` and now I'm getting this error:
```
$ npm run dev

> my-nextron-app@1.0.0 dev C:\Users\dillon\dev\est2
> nextron

ready - started server on http://localhost:8888
TypeError: Cannot read property 'tap' of undefined
    at C:\Users\dillon\dev\est2\node_modules\@next\react-refresh-utils\ReactRefreshWebpackPlugin.js:100:61
    at SyncHook.eval [as call] (eval at create (C:\Users\dillon\dev\est2\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (C:\Users\dillon\dev\est2\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.newCompilation (C:\Users\dillon\dev\est2\node_modules\next\node_modules\webpack\lib\Compiler.js:631:26)
    at C:\Users\dillon\dev\est2\node_modules\next\node_modules\webpack\lib\Compiler.js:667:29
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\dillon\dev\est2\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\dillon\dev\est2\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.compile (C:\Users\dillon\dev\est2\node_modules\next\node_modules\webpack\lib\Compiler.js:662:28)
    at C:\Users\dillon\dev\est2\node_modules\next\node_modules\webpack\lib\Watching.js:77:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\dillon\dev\est2\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
```

Can anyone else reproduce this or is it just me?

**Comment by Psycokwet** [comment]
I tried and I did reproduce the problem. Which is weird since I started the same example a few days agos and it works fine :o

**Comment by Psycokwet** [comment]
I tried to reproduce what I did a few days ago, so : 
npx create-nextron-app my-app --example with-javascript-material-ui
yarn
yarn dev

Works fine here, still today !

**Comment by Psycokwet** [comment]
Deleting node_modules folder, to launch yarn then npm run dev fix the issue too.

The issue seems to be from the use of npm install. When I delete node_modules and use npm install, the issue come back.

I get the same issue with my whole project that I started with this examples a few days ago.

**Comment by dillonco** [comment]
Thank you for trying it and finding a solution! Yarn fixed it for me

**Comment by lailo** [comment]
I'm having the same error. I tried the solution with deleting `node_modules` and using `yarn install` and `yarn dev` but as soon as I stopped the process and tried to re-run `yarn dev` or `npm dev`, I get the same error again.

**Comment by saltyshiomix** [comment]
@dillonco 

Thank you for your reporting the issue.

Try `npm install --save webpack@4.44.0` and will fix this error.

I use yarn so I didn't encounter this problem when I upgraded `webpack` to `v5.2.0`.
(But `next@9.5.1` is powered by `webpack@4.44.0`.)

Npm prefers to the user root package version, on the other hand yarn checks the version of the lib which the author decided.
(I think yarn is better.)


@Psycokwet 

Big thanks to your support :)

**Comment by lailo** [comment]
Thanks for the quick reply @saltyshiomix. Going back to `webpack@4.44.0` solve the problem for me. 
I also tried to update to `next@10.0.0` and kept the original `webpack@5.2.0` but had the same issue with `tap`.

**Comment by saltyshiomix** [comment]
@lailo 

`next@10.0.0` is powered by `webpack@4.44.1` so `webpack@5.2.0` produces the error.

See https://github.com/vercel/next.js/blob/v10.0.0/packages/next/package.json

**Comment by saltyshiomix** [comment]
Just released `nextron@5.15.7` which fixes this error.

**Comment by saltyshiomix** [comment]
@lailo 

But please don't use `next@10.0.0` because nextron holds [this problem](https://github.com/saltyshiomix/nextron/issues/95).

Currently I try to investigate it and I want any help on this.

**Comment by saltyshiomix** [comment]
We can use `next@10.0.2` now 👍 
(It depends on `webpack@4.44.1` so we should not add any versions above.)

**Comment by tunderix** [comment]
For me, the problem was that I was using too old NodeJS. Updated NodeJS -> All is well....
