### ISSUE TITLE
Does Nextron support deploy to App Store, Windows Store & Snap Store?

### ISSUE THREAD

**Issue by mqtik** [saltyshiomix/nextron#125]
Hi, currently I'm rewriting an existing app published on stores and I decided to go with Nextron.

But I don't see any documentacion about deploy to stores.

Is this supported or in the scope?

**Comment by saltyshiomix** [comment]
Hi @mqtik , thank you for your question!

Nextron uses [electron-builder](https://www.electron.build/) so it supports many stores to publish :)

See the [configuration](https://www.electron.build/configuration/configuration) document like:

- [AppX](https://www.electron.build/configuration/appx)
- [Snap](https://www.electron.build/configuration/snap)
