### ISSUE TITLE
App notarization for iOS

### ISSUE THREAD

**Issue by m-w-d-d** [saltyshiomix/nextron#126]
Hi @saltyshiomix,

I was wondering if you had any tips of the best way to notarize apps for iOS that are built using Nextron at all? The build set up is slightly different to other Electron set ups and am wondering if you had any suggestions to work with your set up.

Thanks for your work on this, its incredibly helpful!

**Comment by m-w-d-d** [comment]
I figured this out so no need to reply, thanks!

**Comment by ramzitm91** [comment]
can you tell me how you resolve this? thanks!

**Comment by bm777** [comment]
[https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution?language=objc](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution?language=objc)
