### ISSUE TITLE
TailwindCSS config is ignored

### ISSUE THREAD

**Issue by lailo** [saltyshiomix/nextron#127]
I've added TailwindCSS to the Typescript template based on this repository: https://github.com/vercel/next.js/tree/canary/examples/with-tailwindcss.

The problem I'm having is that all config added to `tailwind.config.js` is ignored. For example, I'm extending a custom primary color, but that does not existing.

`tailwind.config.js`
```js
const { fontFamily } = require('tailwindcss/defaultTheme')

module.exports = {
  future: 'all',
  purge: ['./{components|pages|layout}/**/*.{js,ts,jsx,tsx}'],
  theme: {
    container: {
      center: {
        padding: '2rem',
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter var', ...fontFamily.sans],
      },
      colors: {
        primary: '#FF7A00',
      },
    },
  },
  variants: {},
  plugins: [require('@tailwindcss/ui'), require('@tailwindcss/typography')],
}

```

`postcss.config.js`
```js
module.exports = {
  plugins: ['tailwindcss', 'postcss-preset-env'],
}

```

`pages/_app.tsx`
```js
import '../styles/index.css'
```

**Comment by dac09** [comment]
Try this is in your **postcss config**

```
module.exports = {
  plugins: {
    tailwindcss: require('./tailwind.config'),
    autoprefixer: {},
  },
}
```

**Comment by lailo** [comment]
Thanks a lot @dac09, your input fixed the problem. 
For all the others having this problem, my final postcss config looks like this:

```js
module.exports = {
  plugins: {
    tailwindcss: require('./tailwind.config'),
    'postcss-preset-env': true,
  },
}
```

**Comment by dac09** [comment]
No problem at all! Just recently figured this out myself :)
