### ISSUE TITLE
Add option to `nextron build` to only code bundle and not run electron-builder?

### ISSUE THREAD

**Issue by codetheweb** [saltyshiomix/nextron#129]
I'm currently using a [GitHub Action](https://github.com/samuelmeuli/action-electron-builder) to run Electron Builder, so it would be really nice if there was a way to run the code bundling part of `nextron build` without running Electron Builder as well.

If you're ok with it, I'm happy to make a PR for this.

**Comment by saltyshiomix** [comment]
Hi @codetheweb , sorry for late reply.

I'm really happy for your PR of this :)

**Comment by codetheweb** [comment]
I'm no longer using that specific action and so no longer have this problem, but I imagine it could be useful in other cases as well.

I currently have no plans to make a PR for this, but if I run into the same issue again I'll take a look.

**Comment by saltyshiomix** [comment]
@codetheweb 

Ok, I'll close this issue but if you have any troubles, feel free to make a new issue or PR :)
