### ISSUE TITLE
Add webpack configuration

### ISSUE THREAD

**Issue by Psycokwet** [saltyshiomix/nextron#130]
Hello !
As I would like to use svg files into my code, I'm trying to follow this https://blog.logrocket.com/how-to-use-svgs-in-react/#:~:text=SVGs%20can%20be%20imported%20and,%7D%20from%20'.%2Flogo.

When it say to add configuration to webpack

```javascript
const webpack = require('webpack');

module.exports = {
  entry: './src/index.js',
  module: {
    rules: [
      //...
      {
        test: /\.(png|jp(e*)g|svg|gif)$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: 'images/[hash]-[name].[ext]',
            },
          },
        ],
      },
    ],
  },
  //...
};

```

I don't know how to do that since I can't find where is the webpack configuration in nextron. 

How can I do that then?

**Comment by Psycokwet** [comment]
Ok, I managed to do what I needed without svg, and even so, I figured out that the webpack configuration is in node modules anyway so, maybe not the best move to touch it ahah.

**Comment by saltyshiomix** [comment]
@Psycokwet 

Sorry for late reply.

Please use [nextron.config.js](https://github.com/saltyshiomix/nextron#nextronconfigjs) :)

**Comment by Psycokwet** [comment]
Oh, ok, thank you ! :)
