### ISSUE TITLE
Where can I put png files?

### ISSUE THREAD

**Issue by Psycokwet** [saltyshiomix/nextron#131]
Hello there !

I'm trying to show other png files into my app, than the "logo.png" that there originally is.
I can print "logo.png" withou issue, but no other files. I tried adding files into app/images/ but whatever I do in it, there is no impact on the program. I even replaced the originial "logo.png" by another file, and it's still the exact same "logo.png" that is printed, so how can I use my own png files?

**Comment by Psycokwet** [comment]
Sorry, my fault, I found my way now...
\renderer\public\images

**Comment by Ngomana** [comment]
It does seem to be working for me.

**Comment by Psycokwet** [comment]
Yup, for me too ! That why it's a closed issue, I was just beginning and very lost ! ^^

**Comment by Ngomana** [comment]
Could you please reopen the issue.

**Comment by Psycokwet** [comment]
Why? If it's working for you and me?

**Comment by Ngomana** [comment]
Never mind
