### ISSUE TITLE
Fatal error after yarn install, when yarn dev

### ISSUE THREAD

**Issue by Psycokwet** [saltyshiomix/nextron#134]
![image](https://user-images.githubusercontent.com/14911120/100384172-ce686680-301f-11eb-8de6-5ec049479f67.png)
As of today, this is what happen when I clone my repository based on nextron. I tried to clone new nextron examples as well, and the command yarn takes... Super long to finish. As I was writing this message, I could not see its end yet.

projects\my-app> yarn
yarn install v1.22.5
info No lockfile found.
[1/4] Resolving packages...
warning next > mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning next > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning next > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning next > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning next > resolve-url-loader > rework > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning next > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning next > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > next@9.5.1" has incorrect peer dependency "react@^16.6.0".
warning " > next@9.5.1" has incorrect peer dependency "react-dom@^16.6.0".
warning "next > @next/react-dev-overlay@9.5.1" has incorrect peer dependency "react@^16.9.0".
warning "next > @next/react-dev-overlay@9.5.1" has incorrect peer dependency "react-dom@^16.9.0".
warning "next > styled-jsx@3.3.0" has incorrect peer dependency "react@15.x.x || 16.x.x".
warning "next > use-subscription@1.4.1" has incorrect peer dependency "react@^16.8.0".
[4/4] Building fresh packages...
[3/3] ⠐ electron
[2/3] ⠐ @ampproject/toolbox-optimizer
[-/3] ⠈ waiting...

On Mac (catalina), it tooks 69783.43 secondes to completes the command yarn.
So, I will go ahead and guess that I may have the same issue on windows here.

What happened? Does anyone have issue with new clean work folder ? (node_modules fully reinstalled by yarn)

**Comment by Psycokwet** [comment]
Here is my result as a new attempt from using a blank example :

PS C:\Users\Socar\Documents\projects> npx create-nextron-app my-appBis --example with-javascri
npx: installed 78 in 4.098s
√ Validating existence...
√ Downloading and extracting...

Done! Run `yarn && yarn dev` inside of "C:\Users\Socar\Documents\projects\my-appBis" to start 
PS C:\Users\Socar\Documents\projects> cd .\my-appBis\
PS C:\Users\Socar\Documents\projects\my-appBis> yarn
yarn install v1.22.5
info No lockfile found.
[1/4] Resolving packages...
warning next > mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update n 1.x.)
warning next > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 
warning next > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be usi
warning next > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will bre
warning next > resolve-url-loader > rework > css > urix@0.1.0: Please see https://github.com/l
warning next > chokidar > braces > snapdragon > source-map-resolve > urix@0.1.0: Please see ht
warning next > chokidar > braces > snapdragon > source-map-resolve > resolve-url@0.2.1: https:
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it 
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it f
[3/4] Linking dependencies...
warning " > @material-ui/core@4.11.1" has incorrect peer dependency "react@^16.8.0".
warning " > @material-ui/core@4.11.1" has incorrect peer dependency "react-dom@^16.8.0".
warning "@material-ui/core > @material-ui/system@4.9.14" has incorrect peer dependency "react@
warning "@material-ui/core > @material-ui/system@4.9.14" has incorrect peer dependency "react-
warning "@material-ui/core > @material-ui/styles@4.11.1" has incorrect peer dependency "react@
ct-dom@^16.6.0".
warning "next > @next/react-dev-overlay@9.5.1" has incorrect peer dependency "react@^16.9.0".   
warning "next > @next/react-dev-overlay@9.5.1" has incorrect peer dependency "react-dom@^16.9.0".
warning "next > styled-jsx@3.3.0" has incorrect peer dependency "react@15.x.x || 16.x.x".       
warning "next > use-subscription@1.4.1" has incorrect peer dependency "react@^16.8.0".
[4/4] Building fresh packages...
success Saved lockfile.
$ electron-builder install-app-deps
  • electron-builder  version=22.9.1
  • loaded configuration  file=C:\Users\Socar\Documents\projects\my-appBis\electron-builder.yml 
Done in 1777.54s.
PS C:\Users\Socar\Documents\projects\my-appBis> yarn dev
yarn run v1.22.5
$ nextron
ready - started server on http://localhost:8888
warn  - ./pages/_app.jsx
Anonymous function declarations cause Fast Refresh to not preserve local component state.       
Please add a name to your function, for example:

Before
export default function () { /* ... */ }

After
export default function Named() { /* ... */ }
info  - ready on http://localhost:8888
________________________________________________________



As you can see, it takes ages to finish the command yarn, and, once the app is launched, the same issue occurs than with my project.

In my project I fixed it by 


npm install -D @babel/plugin-proposal-class-properties
npm install -D @babel/preset-typescript

rm nodes_modules
yarn

npm run dev or yarn dev then works.

I don't know what happened for this problem to occurs, but I saw that there have been recent update on some babel package, so, maybe there is a link? I don't know.

**Comment by Psycokwet** [comment]
This is what happen when I'm trying to do the same with my nextron new starter mentionned above : 


PS C:\Users\Socar\Documents\projects\my-appBis> yarn add dev @babel/plugin-proposal-class-properties
yarn add v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["@babel/plugin-proposal-class-properties@^7.12.1"] is trying to unpack in the same destination "C:\\Users\\Socar\\AppData\\Local\\Yarn\\Cache\\v6\\npm-@babel-plugin-proposal-class-properties-7.12.1-a082ff541f2a29a4821065b8add9346c0c16e5de-integrity\\node_modules\\@babel\\plugin-proposal-class-properties" as pattern ["@babel/plugin-proposal-class-properties@7.12.1"]. This could result in non-deterministic behavior, skipping.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
error inotify@1.4.6: The platform "win32" is incompatible with this module.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
PS C:\Users\Socar\Documents\projects\my-appBis>

**Comment by Psycokwet** [comment]
The long delay disappear with my fix, and the blank example runs fines with it.

**Comment by Psycokwet** [comment]
Update : The long delay seems to have disappeared even without my fix, but, blank example still need it to run without the error in my first screenshot

**Comment by mrgoonie** [comment]
Confirmed that installing `@babel/plugin-proposal-class-properties` and `@babel/preset-typescript` in devDependencies work, thanks @Psycokwet 😄

**Comment by mrgoonie** [comment]
Actually you can just do `yarn add @babel/plugin-proposal-class-properties @babel/preset-typescript` then it should work, no need to install into the devDependencies 😸

**Comment by Psycokwet** [comment]
Certainly ahah. Glad it helped anyway !
I'm still curious on what happened, I hope @saltyshiomix  would have some ideas ^^

**Comment by saltyshiomix** [comment]
My `yarn install` finished in `59.32s`, but it needs to be fixed as @Psycokwet mentioned by installing ``

I got it that these PRs ( #98 #100 ) makes this problem.

I'll add the custom `.babelrc` support for the main process in the next minor release.

**Comment by saltyshiomix** [comment]
Just released `nextron@5.15.14` which should fix this issue.

@Psycokwet @mrgoonie 
Could you try the latest nextron if you have some time?

**Comment by saltyshiomix** [comment]
Also, now we can remove unnecessary libraries like this:

**before**

```json
{
  "devDependencies": {
    "@babel/core": "^7.12.7",
    "babel-loader": "^8.2.1",
    "electron": "^11.0.2",
    "electron-builder": "^22.9.1",
    "next": "9.5.1",
    "nextron": "^5.15.11",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "webpack": "4.44.0"
  }
}
```

**after**

```json
{
  "devDependencies": {
    "electron": "^11.0.2",
    "electron-builder": "^22.9.1",
    "next": "9.5.1",
    "nextron": "5.15.14",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  }
}
```

**Comment by mrgoonie** [comment]
That escalated quickly @saltyshiomix , thanks for your prompt action! <3

**Comment by saltyshiomix** [comment]
Thanks @mrgoonie :)

**Comment by Psycokwet** [comment]
I tested it too, no problem from my side either. Thank you @saltyshiomix  :)
