### ISSUE TITLE
remote-require example no longer works

### ISSUE THREAD

**Issue by kevireilly** [saltyshiomix/nextron#146]
On macOS, it appears as though the remote-require [example](https://github.com/saltyshiomix/nextron/tree/master/examples/remote-require) may no longer work like expected. Related but not, the ipc-communication example does appear to work.

```
 $ yarn create nextron-app nextron-remote-require --example remote-require
 $ cd nextron-remote-require && yarn && yarn dev
 $ // notice no config message is output
```

**Comment by saltyshiomix** [comment]
It is related to https://github.com/electron/electron/issues/21408

**Comment by saltyshiomix** [comment]
I decided to remove this example because of security issues and because this will be deprecated.
Electron provides [`ipcRenderer`](https://www.electronjs.org/docs/api/ipc-renderer) and we can achieve almost of all cases :)

**Comment by saltyshiomix** [comment]
Alternatively we can use [`@electron/remote`](https://github.com/electron/remote) instead of `require('electron').remote`.

**Comment by kevireilly** [comment]
Aha, good call and thanks for having a look. 

The only thing is that I ended up there because it wasn’t apparent what I was missing. Wondering if leaving a notice/readme might be good, but I totally understand the stance.

**Comment by saltyshiomix** [comment]
You are totally good and sorry for the inconvenience.

I'll improve documents step by step :)
