### ISSUE TITLE
How does work with M1 Chip

### ISSUE THREAD

**Issue by CagatayXx** [saltyshiomix/nextron#148]
Hi everyone, as you can see in the title I would like to ask about M1 chip. Is there any update about compatibility with this chip or is that gonna be?
And I gotta say, found this library new. Is that safe. Sorry for this question but told you, I found this just 3 minutes ago and it's working very well :D

**Comment by Psycokwet** [comment]
Hello !

Well, it seem to work without rosetta? So, I guess it is compatible ? I'm not and expert though

**Comment by CagatayXx** [comment]
Okay thank you, by the way, I researched it a little more, and found Electron has started to support M1 chip, you can say arm64 with --arch tag.
And FYI as Electron's say, all of arch support is this: ia32, x64, armv7l, arm64, mips64el

**Comment by steveruizok** [comment]
Hi @CagatayXx, could you expand on your solution? What does your build script read? Standard one below for reference.

```json
"build:mac": "nextron build --mac --x64",
```

**Comment by steveruizok** [comment]
This now works fine, by the way. I just had to update `electron-builder`.

**Comment by saltyshiomix** [comment]
@CagatayXx @steveruizok 
Thank you for reporting the issue!
I hope it works well :)

@Psycokwet 
Thank you as always!
