### ISSUE TITLE
Tailwind customization doesn't work

### ISSUE THREAD

**Issue by daniboomerang** [saltyshiomix/nextron#156]
Trying to use Tailwind with Nextron, but customization isn't working
- Install/Run the `/with-typescript-tailwindcss` example https://github.com/saltyshiomix/nextron/tree/master/examples/with-typescript-tailwindcss
- Try to use the already defined color `accent-1` https://github.com/saltyshiomix/nextron/blob/master/examples/with-typescript-tailwindcss/renderer/tailwind.config.js#L7 in the code.

If I use it as a `className` , for instance here
`<span className='text-accent-1'>⚡ Electron ⚡</span>`

The color is not taking any effect

If I try to apply it the css
```
html,
body {
  @apply bg-gray-900 text-accent-1;
}
```

I get the following error
<img width="511" alt="Screenshot 2021-03-03 at 19 32 38" src="https://user-images.githubusercontent.com/3329046/109861496-42d22780-7c57-11eb-880d-a2dd9423ab8f.png">

Finally if I try to add any custom color following the instructions here https://tailwindcss.com/docs/customizing-colors

![Screenshot 2021-03-03 at 20 56 13](https://user-images.githubusercontent.com/3329046/109871285-f55bb780-7c62-11eb-8d73-7ef89bf2729f.png)

It doesn't work

The thing is, I have a Nextjs project using tailwind in this exact way and it works. That's the main reason I'm opening this issue.

**Comment by daniboomerang** [comment]
I've been investigating this a little bit more.
At first I thought it was an issue on Nextron. But I've tried to configure Tailwind in this example https://github.com/vercel/next.js/tree/master/examples/with-electron-typescript

And I get the same issue.
I can use Tailwind classes, what I can't do is 
- Neither using custom tailwind classes defined in `tailwind.config.js`
- Or use @apply rule on css/less files for custom classes defined in `tailwind.config.js`

There are so few examples around...I can't figure this out.
It looks to me it's related with the order in which things happen
It looks like at runtime the custom classes that should have been generated by tailwind are not there
In fact I can confirm they are not there, as I can see in the element web inspector my html using a custom tailwind class, however the style is not there.

There is something going on in electron main and the way at runtime css is loaded that Tailwind classes are not created and imported to the compiled css

I'd really appreciate some help here...

Regards

**Comment by daniboomerang** [comment]
I figured it out.
It was pretty simple actually.
The issue is in electron projects, the whole web project is placed under a folder renderer.
But the package.json of the project is placed at the root

├── .package.json
├── renderer
    ├── tailwind.config.json
    └── postcss.config.json
    └── etc...


The issue is that tailwind is expecting the tailwind.config.json file  to be at the root folder.

This can be easily fixed by moving `tailwind.config.json` and `postcss.config.json` to the root folder.
However I'd love to keep them inside the rendered folder, cause it's the web project...

Do you know if it's possible to tell tailwind to go find the config files to a different path other than the package.json  root folder?

**Comment by daniboomerang** [comment]
A key in package.json for postcss makes it
```
"postcss": {
    "plugins": {
      "tailwindcss": { "config": "./renderer/tailwind.config.js" }
    }
  },
  ```

**Comment by Dnguye92** [comment]
> A key in package.json for postcss makes it
> 
> ```
> "postcss": {
>     "plugins": {
>       "tailwindcss": { "config": "./renderer/tailwind.config.js" }
>     }
>   },
> ```

@daniboomerang you added this to `package.json`???

**Comment by CreedDE** [comment]
@Dnguye92 Yep, just paste it into your package.json.
postcss accept different methods of configs. one of them is the `postcss.config.js` and `package.json` format.

You can just do it in the `postcss.config.js` like that:
```js
require('autoprefixer');

module.exports = {
  plugins: {
    tailwindcss: { config: './renderer/tailwind.config.js' },
    autoprefixer: {},
  },
};
```

**Comment by daniboomerang** [comment]
@Dnguye92 yes.
But @CreedDE proposal sounds good too! Didn't know that you can pass the config file in `postcss.config.js`
Thanks for the info

**Comment by daniboomerang** [comment]
@Dnguye92 although this fix the issue I had in dev, I'm now struggling getting this to work in the dist app.
In this project I import some some own css as well as Antd dark theme and Tailwind

`_app.tsx`
```
import { ReactElement } from 'react'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { DashboardLayout } from '@components/layout'
import 'tailwindcss/tailwind.css'
import 'antd/dist/antd.dark.less'
import '../styles/index.less'

const MyApp = ({ Component, pageProps }: AppProps): ReactElement => (
```

The issue is easy to describe.
1- I run `yarn build:mac` 
2- I check the resulted built nextjs app and I see 4 css compiled and one of them contains my custom tailwind. As you can see in the following screenshot, a compiled css with my custom color `moodyBlue` is in the nextjs built app.

<img width="902" alt="Screenshot 2021-03-27 at 23 41 52" src="https://user-images.githubusercontent.com/3329046/112737057-8b77ba80-8f4f-11eb-9ff2-6e70a3fef71a.png">

3- I open the resulted macOS app and all Tailwind styles are missing...

Antd and my custom css perfectly loads. But tailwind is gone. Completely. Not even the default tailwind CSS.
I'm missing tailwind completely.

I don't know what I'm missing here. If the css is present in the built next js app....shouldn't just the generation of the app in macOS just wrap that Nextjs app with those css? (Including the tailwind one)?

I think I'm missing some basic thing here...
I'd appreciate some help.

**Comment by CreedDE** [comment]
@daniboomerang I found a solution but idk if its really a solution, feels more like a workaround :D 

my new config:
postcss.config.js 
```js
module.exports = {
  plugins: {
    tailwindcss: { config: './renderer/tailwind.config.js' },
    autoprefixer: {},
  },
};
```


tailwind.config.js
```js
module.exports = {
  //   darkMode: 'media', // 'media' or 'class' to enable dark mode support
  theme: {
    extend: {
      colors: {
        'accent-1': '#333',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

remove the purge setting completely.
I think its not an ideal fix, but it works for me.
Also its necessary to add the path to the tailwind config in postcss

**Comment by saltyshiomix** [comment]
Hi there, sorry for late reply.

Please consider to follow [official guidelines](https://tailwindcss.com/docs/guides/nextjs) and its [example](https://github.com/vercel/next.js/tree/master/examples/with-tailwindcss).

**Comment by daniboomerang** [comment]
Hi @saltyshiomix
The issue is related with Nextjs and Tailwind **in the context of electron/nextron**

 As described, the issue is tailwind custom customization isn't working in the official examples provided by Nextron
 https://github.com/saltyshiomix/nextron/tree/master/examples/with-typescript-tailwindcss

**Comment by saltyshiomix** [comment]
@daniboomerang 

Thank you for your reply!

Ok I'll investigate as soon as I can.

**Comment by daniboomerang** [comment]
I think the issue has been resolved here
https://github.com/saltyshiomix/nextron/pull/165/commits/3398f5fc78a53c722b75e92002a855164112a4dd

**Comment by saltyshiomix** [comment]
Merged #165 into master :)

**Comment by daniboomerang** [comment]
@saltyshiomix I see you have removed custom classes from the tailwind examples
https://github.com/saltyshiomix/nextron/commit/119aa3b9136de64a1dba380401774740d52979e7#diff-961fc2497f5b07d8a1f6fc97797820f81f56ace03b1476f0c3033aa68567813aL5-L9

I believe that is the key point to prove nextron and custom customization of tailwind works
I'd recommend to put back the `accent-1` custom class un the js and ts tawilwind examples

**Comment by saltyshiomix** [comment]
@daniboomerang @Dnguye92 @CreedDE 

Sorry for late reply.

Just updated tailwindcss examples (bump v2 => v3), and we can finally use `@apply` or any directives 👍 

**postcss.config.js**

```js
module.exports = {
  plugins: {
    tailwindcss: {
      config: './renderer/tailwind.config.js',
    },
    autoprefixer: {},
  },
};
```

**tailwind.config.js**

```js
const colors = require('tailwindcss/colors');

module.exports = {
  content: [
    './renderer/pages/**/*.{js,ts,jsx,tsx}',
    './renderer/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    colors: {
      // use colors only specified
      white: colors.white,
      gray: colors.gray,
      blue: colors.blue,
    },
    extend: {},
  },
  plugins: [],
};
```

**styles/globals.css**

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  body {
    @apply bg-gray-900 text-white;
  }
}

@layer components {
  .btn-blue {
    @apply text-white font-bold px-4 py-2 rounded bg-blue-600 hover:bg-blue-500;
  }
}
```
