### ISSUE TITLE
Build executable icon change

### ISSUE THREAD

**Issue by Besuf** [saltyshiomix/nextron#162]
I have managed to change the software icon while its being run.  I have tried replacing the files inside resources but no luck, It dont seem to change the icon of the executable file after build. is there any other way to change the executable file icon maybe inside build script?
@saltyshiomix  very helpful library btw. Thanks.

**Comment by dac09** [comment]
Hey @Besuf not sure if this will help you, but this is how I have it configured.

In my `electron-builder.yml` 

```diff
productName: Tape
copyright: Copyright © 2020 Daniel Choudhury
directories:
  output: dist
+  buildResources: buildResources
```

And I have my icons along with other build resources there:
```
./buildResources
├── entitlements.mac.inherit.plist
├── icon.icns
└── icon.ico
```

Hope this helps!

**Comment by saltyshiomix** [comment]
@Besuf 
Sorry for late reply.
It may be the cache problem, which I encountered before.

https://github.com/electron-userland/electron-builder/issues/840
https://github.com/electron-userland/electron-builder/issues/2062

Feel free to reopen the issue if any troubles :)

@dac09 
Thank you for your advice!
