### ISSUE TITLE
npm init with-javascript-tailwindcss template does nothing

### ISSUE THREAD

**Issue by karimhossenbux** [saltyshiomix/nextron#166]
I tried to `npm init nextron-app moonitor-next --example with-javascript-tailwindcss` but I don't the config from the `example/with-javascript-tailwindcss`.

Looks like I get the one from the root repo:

```
"dependencies": {
    "electron-serve": "^1.1.0",
    "electron-store": "^7.0.2"
  },
  "devDependencies": {
    "electron": "^11.3.0",
    "electron-builder": "^22.9.1",
    "next": "^10.0.7",
    "nextron": "^6.0.4",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  }
```

I've also tried with `with-javascript-ant-design` but it's the same result. I always get the root repo files.

```
npm -v: 7.4.3 
node -v: 15.7.0
```

---

Thank you for that repo though, it will be very useful 🙌

**Comment by saltyshiomix** [comment]
@karimhossenbux 

Thank you for reporting the issue.
I can reproduce this bug so I'll investigate it soon.

Until it fixed, please consider to use Node.js `v14` :)

**Comment by saltyshiomix** [comment]
I found the solution:

- ok: `yarn create nextron-app`
- ok: `npx create-nextron-app`
- ng: `npm init nextron-app`

So please use `npx` or `yarn`.

I'll fix the document, too.
