### ISSUE TITLE
Cannot use electron 12 without `contextIsolation: false`

### ISSUE THREAD

**Issue by dac09** [saltyshiomix/nextron#170]
Hi again 👋

So I've tried upgrade my project to electron 12.x, but get 

```
ReferenceError: require is not defined
```

In order to solve this, I had to disable `contextIsolation` in create-window
```diff
const browserOptions: BrowserWindowConstructorOptions = {
    ...options,
    ...state,
    webPreferences: {
      nodeIntegration: true,
+      contextIsolation: false,
      ...options.webPreferences,
      preload: path.join(__dirname, '../resources/sentryPreload.js'),
    },
  }
```

This was a breaking change introduced in electron 12. However, I'm wondering why I need contextIsolation to be disabled in nextron?

I've tried it in dev, and after a build, in both cases I need to have contextIsolation set to false, otherwise it errors out.

Links:
https://github.com/electron/electron/blob/master/docs/tutorial/context-isolation.md

---
Relevant dependency versions
```
 "electron": "^12.0.2",
 "electron-builder": "^22.10.5",
  "next": "^10.1.3",
  "nextron": "^6.0.6",
```

**Comment by jawil003** [comment]
If you are using `contextIsolation: true` that disables node.js modules in renderer. You need to inject functions in the window object through preload scripts then.

This is not related to nextron, but a general electron behavior.

**Comment by prvnbist** [comment]
@dac09 Did you manage to find a  solution? I'm stuck at the similar problem.

**Comment by dac09** [comment]
> @dac09 Did you manage to find a solution? I'm stuck at the similar problem.

I'm afraid not - oddly I'm not using nodejs modules on the renderer side (but using the IPC bridge to invoke it where required)

**Comment by prvnbist** [comment]
I've come across similar solution, using ipcRenderer to invoke the handle.

**Comment by ObadaZay** [comment]
> @prvnbist I've come across similar solution, using ipcRenderer to invoke the handle.
Could you please share it with us?

**Comment by saltyshiomix** [comment]
@dac09 CC: @sustainjane98 @prvnbist @ObadaZay 

Sorry for late reply 🙇 

Please remove `config.target = 'electron-renderer'` in `next.config.js`:

**Before**

```js
module.exports = {
  trailingSlash: true,
  images: {
    unoptimized: true,
  },
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.target = 'electron-renderer'
    }

    return config
  },
}
```

**After**

```js
/** @type {import('next').NextConfig} */
module.exports = {
  trailingSlash: true,
  images: {
    unoptimized: true,
  },
  webpack: (config) => {
    return config
  },
}
```

Finally, we can set `contextIsolation: true`:

```ts
const win = new BrowserWindow({
  ...state,
  ...options,
  webPreferences: {
    ...options.webPreferences,
    nodeIntegration: false,
    contextIsolation: true,
  },
})
```

Also, we updated whole examples, so if you have time please check new examples 🙇 

Feel free to reopen the issue if you have any troubles :)
