### ISSUE TITLE
Can't purge TailwindCSS?

### ISSUE THREAD

**Issue by herbievine** [saltyshiomix/nextron#174]
I just created a project and was configuring Tailwind, but the prod build is missing styles when purge is activated... I have it set to purge files in the pages directory (`'./pages/**/*.(ts|js|tsx|jsx)'`)

**Comment by herbievine** [comment]
After further inspection, it only seems to be happening on styles in a component (e.g. `className="text-red-500"`). Styles applied within the `styles/globals.css` file with tailwind's `@apply` works fine...

**Comment by ElijahJohnson5** [comment]
I had to set the path to be `'./renderer/pages/**/*.(ts|js|tsx|jsx)'` and similarly for components.

**Comment by saltyshiomix** [comment]
@herbievine CC: @ElijahJohnson5 

Sorry for late reply.

Just updated tailwindcss examples (bump v2 => v3), and we can finally use `@apply` or any directives 👍 

**postcss.config.js**

```js
module.exports = {
  plugins: {
    tailwindcss: {
      config: './renderer/tailwind.config.js',
    },
    autoprefixer: {},
  },
};
```

**tailwind.config.js**

```js
const colors = require('tailwindcss/colors');

module.exports = {
  content: [
    './renderer/pages/**/*.{js,ts,jsx,tsx}',
    './renderer/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    colors: {
      // use colors only specified
      white: colors.white,
      gray: colors.gray,
      blue: colors.blue,
    },
    extend: {},
  },
  plugins: [],
};
```

**styles/globals.css**

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  body {
    @apply bg-gray-900 text-white;
  }
}

@layer components {
  .btn-blue {
    @apply text-white font-bold px-4 py-2 rounded bg-blue-600 hover:bg-blue-500;
  }
}
```
