### ISSUE TITLE
Webpack 5 through NextJs Future option

### ISSUE THREAD

**Issue by ElijahJohnson5** [saltyshiomix/nextron#179]
I have been trying to get nextron to work with the webpack 5 option enabled in next.config.js. Is there any suggestions on how to get this working?

**Comment by kierancrown** [comment]
Change the next.config.js in the renderer directory to look like this

```(javascript)
module.exports = {
  future: {
    webpack5: true,
  },
  webpack: (config) =>
    Object.assign(config, {
      target: "electron-renderer",
    }),
};
```

**Comment by ElijahJohnson5** [comment]
For anyone else having trouble with this I got it working with this `next.config.js`. It seems like the server next.js webpack config cannot be targeted to electron renderer anymore.

```
module.exports = {
  future: {
    webpack5: true,
  },
  webpack: (config, {  isServer }) => {
    if (isServer) {
      return config;
    }

    return Object.assign(config, {
      target: 'electron-renderer',
    });
  },
};

```

**Comment by saltyshiomix** [comment]
@ElijahJohnson5 

Thank you for reporting the issue and giving the good solution!

Just released nextron v7, could you try it?

**Comment by saltyshiomix** [comment]
I think nextron v7 supports webpack v5 for now, so I close this issue.

If any troubles, feel free to reopen the issue :)
