### ISSUE TITLE
Can't pull environment variables in TypeScript + Tailwind project

### ISSUE THREAD

**Issue by Dnguye92** [saltyshiomix/nextron#188]
I created a `.env` file in root with a hand full of `NEXT_PUBLIC_` environment variables. Trying to log them from `/pages/index.tsx` but I'm not seeing any of them.

Any clue?

**Comment by saltyshiomix** [comment]
@Dnguye92 

I think we should locate `.env` file in the **renderer** folder.

Could you try it?

**Comment by FransSlabbekoorn** [comment]
You can load the environment variables into process.env using the dotenv package
You should load them in the main process (background.js) like this:

```typescript
import { config } from 'dotenv';
import isDev from 'electron-is-dev';

config({
    path: isDev ? '.env.development' : '.env.production',
});
```

.env: 
```env
NODE_ENV="development"
CUSTOM_VAR=123
NEXT_PUBLIC_CUSTOM_VAR=456
```

When prefixed with NEXT_PUBLIC_ you can access them in the renderer/next.js process

**Comment by saltyshiomix** [comment]
If any troubles or updates, feel free to reopen the issue 🙏

**Comment by jt-l** [comment]
> You can load the environment variables into process.env using the dotenv package You should load them in the main process (background.js) like this:
> 
> ```ts
> import { config } from 'dotenv';
> import isDev from 'electron-is-dev';
> 
> config({
>     path: isDev ? '.env.development' : '.env.production',
> });
> ```
> 
> .env.development:
> 
> ```dotenv
> NODE_ENV="development"
> CUSTOM_VAR=123
> NEXT_PUBLIC_CUSTOM_VAR=456
> ```
> 
> When prefixed with NEXT_PUBLIC_ you can access them in the renderer/next.js process

This does not appear to work for builds, e.g., 'nextron build' -- any thoughts?

**Comment by frans-slabbekoorn** [comment]
I'm currently not using nextron, when I get back to it i will take a look at this. Sorry!
