### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by oSethoumOld** [saltyshiomix/nextron#190]
Hello, 
Can you add example with Chakra UI and Typescript together, I have tried to make them work but couldn't.

**Comment by hypernova7** [comment]
You can use this [example](https://github.com/vercel/next.js/tree/canary/examples/with-chakra-ui-typescript) (I hope and it will serve you), just remember that everything must go inside the renderer folder

**Comment by saltyshiomix** [comment]
I think @hypernova7 's way is correct 👍 

@oSethoumOld 
If any troubles, feel free to reopen the issue :)

**Comment by hems** [comment]
> You can use this [example](https://github.com/vercel/next.js/tree/canary/examples/with-chakra-ui-typescript) (I hope and it will serve you), just remember that everything must go inside the renderer folder

i believe now this example must be used instead:

https://github.com/vercel/next.js/tree/canary/examples/with-chakra-ui

Would be good to get it featured on the README file like the other examples!

chakra-ui is definitely one of the best options nowadays
