### ISSUE TITLE
How to add a javascript dom lib

### ISSUE THREAD

**Issue by Psycokwet** [saltyshiomix/nextron#191]
Hello !

I have a library that I'm trying to use on the renderer of the project, as I understand, originally with react I'm supposed to follow thoses guidelines : https://reactjs.org/docs/integrating-with-other-libraries.html

But, I have to have access to "document" for that, as in this steps I must follow, there is this : 

```javascript
function webphone() {
  ReactDOM.render(<Example />, document.getElementById("root"));
}
```

But, document is not defined. How can I access it within nextron renderer ?

The lib itself tries to access window as well

**Comment by hypernova7** [comment]
Nextron uses Next JS, no need to use react-dom.  Just create your modules or components, as follows:

```javascript
// home.js

import React, { useState } from 'react';

function Home () {
  const [state, setState] = useState(false);
  return (
    <div>
      Hello world!
    </div>
  )
}

export default Home()
```

And run `yarn run dev` or `npm run dev`, and it will automatically render it.

Please visit [NextJS documentation](https://nextjs.org/learn/basics/create-nextjs-app)

**Comment by Psycokwet** [comment]
Yup, I know that, but, this is not possible with this lib, not as i find or tried.

The document of the lib says that we need to do that to use it ;

```html
<head>
<!-- Include the webphone_api.js to your webpage -->
<script src="webphone_api.js"></script>
</head>
<body>
<script>
//Wait until the webphone is loaded, before calling any API functions
webphone_api.onAppStateChange(function (state)
{
if (state === 'loaded')
 {
//Set parameters (Replace upper case worlds with your settings)
//Alternatively these can be also preset in your webphone_config.js file or passed as URL parameters
webphone_api.setparameter('serveraddress', SERVERADDRESS); 
webphone_api.setparameter('username', USERNAME); 
webphone_api.setparameter('password', PASSWORD); 
//See the “Parameters” section below for more options 
//Start the webphone (optional but recommended) 
webphone_api.start();
//These API calls below actually should be placed behind separate functions (button clicks)
//Make a call (Usually initiated by user action, such as click on a click to call button. Number can be extension, SIP username, SIP URI or mobile/landline phone) 
webphone_api.call(NUMBER); 
//Hang-up (usually called from “disconnect” button click)
webphone_api.hangup(); 
//Send instant message (Number can be extension, SIP username. Usually called from a “send chat” button) 
webphone_api.sendchat(NUMBER, MESSAGETEXT);
 }
});
//You should also handle events from the webphone and change your GUI accordingly (onXXX callbacks)
</script>
</body>
```

But it's not really usable as it is with nextron, because of react first, and then because of the lack of window/document object thanks to electron.

With a simple electron project it does works, do I guess there is a way to make it work with nextron?

**Comment by hypernova7** [comment]
You can use [next/script](https://nextjs.org/docs/basic-features/script)

**Comment by Psycokwet** [comment]
Well, I started reading the doc, and as I tried to use it, I got this error : 
```
Failed to compile
./pages/webphone.jsx
Module not found: Can't resolve 'next/script' in 'C:\Users\<user>\Documents\<project>\renderer\pages'
This error occurred during the build process and can only be dismissed by fixing the error.
```
just when adding this line, to follow the documentation
``` javacript
import Script from "next/script";
```

Is there some configuration missing to use this on nextron ? 
I've never used webpack or next before nextron, So I have no idea what's missing here

**Comment by hypernova7** [comment]
Update NextJS to latest version ;)

`yarn add -DE next react react-dom` or `npm i -DE next react react-dom`

**Comment by Psycokwet** [comment]
Thank you for your suggestion, but now, once updated I get another error : 
```
Server Error
Error: The default export is not a React Component in page: "/home"
```
Even with a new nextron template, unaltered, if I update, I get this error. I did not find relevant info about this issue online :( 

Do you know why that happen ?

**Comment by hypernova7** [comment]
disable webpack5 in nuxt.config.js:

```javascript
module.exports = {
  webpack5: false,
  webpack: (config) => {
    return config;
  }
}
```

**Comment by Psycokwet** [comment]
Hello again !

Thank you for your help ! 
It did work, and I can even manipulate the window object now !

I will try again to add my lib, I hope it will work now !

But, thank you a lot for your help so far :) 
I'm the closest I've been for weeks thanks to you haha. You can't imagine how many things I tried to always fall back into the "window undefined" problem in the end, maybe now it will works fine haha. I hope so.

**Comment by hypernova7** [comment]
I'm glad I helped you, and good luck ;)

**Comment by Psycokwet** [comment]
THANK YOU !
I have been able to import the damned lib thanks to you !
Still not perfect, but, at least I have proven that it does seems to work !

By the way, it weird but, to succeed in loading it, I had to use the <script> instead of next/Script, <Script> had absolutely no effect, whatever I was putting inside for some reason, do you perhaps know why it would happen?

**Comment by hypernova7** [comment]
You can use `useEffect` and `useCallback`, this way

```javascript
import Script from 'next/script';
import { useCallback, useEffect } from 'react';

export default function Home() {
  const onLoad = useCallback(() => {
    useEffect(() => {
      // componentDidMount() like
      // You can access to 'window' object from here
      // window.alert('Hello world')
      webphone_api.onAppStateChange(function (state)
      {
        if (state === 'loaded')
        {
          //Set parameters (Replace upper case worlds with your settings)
          //Alternatively these can be also preset in your webphone_config.js file or passed as URL parameters
          webphone_api.setparameter('serveraddress', SERVERADDRESS); 
          webphone_api.setparameter('username', USERNAME); 
          webphone_api.setparameter('password', PASSWORD); 
          //See the “Parameters” section below for more options 
          //Start the webphone (optional but recommended) 
          webphone_api.start();
          //These API calls below actually should be placed behind separate functions (button clicks)
          //Make a call (Usually initiated by user action, such as click on a click to call button. Number can be extension, SIP username, SIP URI or mobile/landline phone) 
          webphone_api.call(NUMBER); 
          //Hang-up (usually called from “disconnect” button click)
          webphone_api.hangup(); 
          //Send instant message (Number can be extension, SIP username. Usually called from a “send chat” button) 
          webphone_api.sendchat(NUMBER, MESSAGETEXT);
        }
      });
    }, [])
  }, [])

  return (
    <Script src='webphone_api.js' strategy='beforeInteractive' onLoad={onLoad} />
  )
}
```

**Comment by Psycokwet** [comment]
I don't know why, but it still has no effect. No error, no nothing, or at least, nothing I can see.
Webphone_api launch a lot of logging by console log, so, as soon as it's loaded I can see it with the <script> balise, but with <Script>, i see nothing, even If I put some logging into the onLoad function

Even with your code, or just a window alert or what

**Comment by Psycokwet** [comment]
Hello again !

I tried again in a small empty project. The script does load, there is the console.log I was talking about, but, onLoad and onError never get called, do you know why that is ? 
https://github.com/Psycokwet/nextron_lib_onload

Thank you a lot for your help :)

**Comment by hypernova7** [comment]
You could try importing your library as a module instead of using `<Script />` and just using `useEffect` without `useCallback`

```javascript
// webphone_api.js
export default webphone_api
```

```javascript
// home.jsx
import { useEffect } from 'react';
import webphone_api from '../lib/webphone_api';

export default function Home() {
  useEffect(() => {
    // init webphone_api from here
  }, [])
}
````

**Comment by Psycokwet** [comment]
The issues is that webphone_api seems to do a few things with the object window, If I try to import it as you suggessted, it will cause some error because it can't access the window object, since it's not yet initialized

Or did I misunderstand you maybe ?

**Comment by hypernova7** [comment]
Using `useEffect` you can access the `window` object.

[Reference](https://github.com/saltyshiomix/nextron#the-basic-of-react-hooks-)

**Comment by Psycokwet** [comment]
Yes, but not from inside webphone_api :o
Or can I somehow do the import from the useEffect? I thought not?

**Comment by hypernova7** [comment]
You cannot import a module within a function, all imports must be at a level-up.  Unless you use `require`.

_Well if you don't mind I'll delete some comments, so as not to bother the author_

**Comment by Psycokwet** [comment]
Why did you delete some comments? And I'm the author of this issue, why would it bother me ?

Yes, I knew that, but, since webphone_api need the window object defined, to initiate itself (it does a few operation with it), I cannot import it, as it will try to call for the window object, before it is defined (it throws errors on window undefined If I try to import it)

Require does not seem to be possible either, this happen when trying
```
error - ./lib/webphone/webphone_api.js:1056:26
Syntax error: Binding 'arguments' in strict mode
```

**Comment by hypernova7** [comment]
Try this way:
```javascript
// home.jsx
import { useEffect } from 'react';

export default function Home() {
  useEffect(() => {
    window.webphone_api = require('../lib/webphone_api');
  }, [])
}
````

**Comment by Psycokwet** [comment]
Hello !

I tried it, but it's make a lot of path errors, I don't really know how to fix them for good.  Like, webphone_api will use webphone_config, and so on.
To require it, I need to put the folder in the renderer/lib folder, but, once inside webphone_api, it will try to get the dependencies from the renderer/public folder (for some reasons)

Like, I can correct a few pathes to see that it fixes some errors, but, webphone_api is complexe, and "fixing" the path like that seems completely wacky, and it will be hard to maintain to prod for example, as well as i'm not certain I will find how to "fix" them all.

Also, the script webphone api, already add a window.webphone_api = webphone_api once the object is initialized.
I just need to successfully start the script and know once it's done.

**Comment by hypernova7** [comment]
Another way would be to use `import()`
```javascript
import { useEffect, createRef } from 'react';

export default function Home() {
  const input = createRef()

  useEffect(() => {
    loadLib()

    async function loadLib() {
      await import('../lib/webphone_api')
      const webphone_api = window.webphone_api
      window.console.log(input.current.value)
    }
  }, [])

  return (
    <>
      <input type="text" ref={input} />
    </>
  )
}
```
