### ISSUE TITLE
Examples helper file not available

### ISSUE THREAD

**Issue by Lance1997** [saltyshiomix/nextron#197]
In some of the projects there seems to be an import of a file, helpers that is not available in the directory.

I verified this behavior in the store-data example and the ipc-communication example.

Import statement: `import { createWindow } from './helpers';` and is normally found in the `main/background.js` file.

I am not sure if the helper file is the one that's missing or the import statement is what's wrong here.

**Comment by Psycokwet** [comment]
Helper is a folder, you get it and the working example by using the commands on the front page of the project to create a new project from the example. It seems you git clone the whole nextron, that's not how you start a nextron project :)
![Screenshot_20210731-230703_Chrome](https://user-images.githubusercontent.com/14911120/127752412-7902c57b-eacf-408b-966e-9a7879835c69.jpg)

**Comment by Lance1997** [comment]
Thank you very much. Yes I copied and did not use the npx command to launch the project.

**Comment by Psycokwet** [comment]
No problems, welcome to Nextron :)
