### ISSUE TITLE
next.config.js vs nextron.config.js

### ISSUE THREAD

**Issue by sketchbuch** [saltyshiomix/nextron#202]
What is the diffeence between the two? Which should I use? Does it have to b in the project root or can I move it to a diffeent folder? If I can move them, do I need to change any settings?

**Comment by saltyshiomix** [comment]
@sketchbuch 

Sorry for late reply.

The answer is:

- `next.config.js` is for the renderer process (next.js)
- `nextron.config.js` is for the main process (electron)

**Comment by AlexisPiquet** [comment]
@sketchbuch is it solved? If yes, could you close your issue ?

**Comment by saltyshiomix** [comment]
@alexis-piquet 
Thank you for your help so much!

@sketchbuch 
Feel free to reopen the issue if any troubles 🙏
