### ISSUE TITLE
Custom Title Bar

### ISSUE THREAD

**Issue by YeonV** [saltyshiomix/nextron#206]
Hi Bro.

First of all thank you very much for your awesome project!!!!
Im using your master-piece together with typescript-material-ui.

But im failing to implement [custom-electron-titlebar](https://www.npmjs.com/package/custom-electron-titlebar) for days now...
i can make it work in yarn dev
but its failing on yarn build with "navigator is not defined"
i tried 100 of fixes and workarounds, but im too noob :(

I think after fix, maybe this could also be worth to include it in your example-template.

Can you help me with that?
maybe configurable with config or hook

Thank you very much
Gratefully

Blade (aka YeonV)

**Comment by saltyshiomix** [comment]
@YeonV 

Thank you for your reporting the issue :)

I found the solution here:

**main/background.js**

```js
const mainWindow = createWindow('main', {
  width: 1000,
  height: 600,
  titleBarStyle: "hidden", // <-- add this line if needed
  webPreferences: {
    enableRemoteModule: true // <-- add this line
  },
});
```

and **renderer/pages/home.jsx**

```jsx
import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { remote } from 'electron';

function Home() {
  React.useEffect(() => {
    const { Menu, MenuItem } = remote;

    const customTitleBar = require('custom-electron-titlebar');
    const titlebar = new customTitleBar.Titlebar({
      backgroundColor: customTitleBar.Color.fromHex('#444')
    });

    const menu = new Menu();
    menu.append(new MenuItem({
      label: 'Item 1',
      submenu: [
        {
          label: 'Subitem 1',
          click: () => console.log('Click on subitem 1'),
        },
        {
          type: 'separator',
        }
      ]
    }));

    menu.append(new MenuItem({
      label: 'Item 2',
      submenu: [
        {
          label: 'Subitem checkbox',
          type: 'checkbox',
          checked: true,
        },
        {
          type: 'separator',
        },
        {
          label: 'Subitem with submenu',
          submenu: [
            {
              label: 'Submenu &item 1',
              accelerator: 'Ctrl+T',
            },
          ],
        },
      ],
    }));

    titlebar.updateMenu(menu);

    return () => {
      titlebar.dispose();
    };
  }, []);

  return (
    <React.Fragment>
      <Head>
        <title>Home - Nextron (with-javascript)</title>
      </Head>
      <div>
        <p>
          ⚡ Electron + Next.js ⚡ -
          <Link href="/next">
            <a>Go to next page</a>
          </Link>
        </p>
        <img src="/images/logo.png" />
      </div>
    </React.Fragment>
  );
};

export default Home;
```

**Comment by YeonV** [comment]
BAAAM thank you bro!!!
Trying it asap and will report back here

**Comment by YeonV** [comment]
Here it is bro: https://github.com/YeonV/wled-manager

Thanks so much!! ❤️ 

Some noob-questions: 🙈 
Could you give some insights about the folder structure?
(especially regarding images)

- `resources`
- `public/images`
- `renderer/public/images` _i think those gets to_  `app/images`  _on yarn build and can be accessed from main and renderer_
- `src` what about the app and index, are they used?
- last but not least: Can we still build it as nextjs for web?

Sidenote:
the titlebar was killing me for days, and you nailed it in 10min including working code-example....
BIG respect 👍

**Comment by saltyshiomix** [comment]
@YeonV 

I'm glad to hear that :)

With nextron, I recommend these folder structures:

- `resources`: application-wide images (for example, app icons)
- `renderer/public/images`: images for renderer (Next.js)

Because images can be used by only renderer process (Next.js), so I think we should place them in a next.js' way.

Additionally, if we use Next.js, we don't need `src` folder but `renderer` folder.

Thank you for your kind reply :)

**Comment by YeonV** [comment]
@saltyshiomix Hii broo :)

do you know how to make the `yarn next renderer` command work?

I would like to start the inner webproject without the electron wrapper, but it is resulting in an `Uncaught ReferenceError: global is not defined
`
any tips would be awesome <3
