### ISSUE TITLE
Use Sqlite database

### ISSUE THREAD

**Issue by Hulxv** [saltyshiomix/nextron#207]
How to can i use sqlite or another database in my project ?

**Comment by gitE0Z9** [comment]
Is this issue updated? 
I used API route to get access to sqlite in development mode, but this method failed when in production mode.

**Comment by Hulxv** [comment]
> Is this issue updated? 
> I used API route to get access to sqlite in development mode, but this method failed when in production mode.

Use it in backend -Electron- with any library you want like knex and send it to frontend by IpcMain, Because you can't export API route.

You can see how I use it in [vnstat-client](https://github.com/Hulxv/vnstat-client).

**Comment by gitE0Z9** [comment]
Thanks, I figured out that yesterday. Now I am using ipcMain and ipcRenderer to communicate.

One thing still confuses me is `preload.js` won't be found no matter I put it in `main` folder or `renderer` or `app`,
I want to use the file for `contextBridge` feature read on electron documentation.
