### ISSUE TITLE
tailwindcss.config.css not working

### ISSUE THREAD

**Issue by Hulxv** [saltyshiomix/nextron#209]
When try customize something like font or custom color that not working

How can fix this issue ?

**Comment by Hulxv** [comment]
tailwindcss.config.js location in **rerender** directory like example

**Comment by AvIsBeastMC** [comment]
man it's tailwind.config.js not tailwindcss.config.js :)

**Comment by Hulxv** [comment]
> man it's tailwind.config.js not tailwindcss.config.js :)

I know, I meant tailwind.config.js. the important thing is how do I solve this problem

**Comment by AvIsBeastMC** [comment]
> 
> 
> > man it's tailwind.config.js not tailwindcss.config.js :)
> 
> I know, I meant tailwind.config.js. the important thing is how do I solve this problem

oh ok

**Comment by AlexisPiquet** [comment]
Is it solved ? If yes could you close your issue ?

**Comment by Hulxv** [comment]
> Is it solved ? If yes could you close your issue ?

Unfortunately, isn't solved

**Comment by Kaplas85** [comment]
First things, sorry for my bad english.

What are you mean with customize? 

When any customization with tailwind works is because the content don't setup correctly. 

I use `tailwind.config.js` in the root and `postcss.config.js` in renderer folder whit this configuration

``` 
module.exports = {
  plugins: {
    tailwindcss: {
      config: "./tailwind.config.js",
    },
    autoprefixer: {},
  },
};

```
Or you can put the `postcss.config.js` and `tailwind.config.js` in root folder and works fine too!

**Comment by saltyshiomix** [comment]
@Hulxv CC: @alexis-piquet @Kaplas85 

Sorry for late reply.

Just updated tailwindcss examples (bump v2 => v3), and `tailwind.config.js` works fine 👍 

**postcss.config.js**

```js
module.exports = {
  plugins: {
    tailwindcss: {
      config: './renderer/tailwind.config.js',
    },
    autoprefixer: {},
  },
};
```

**tailwind.config.js**

```js
const colors = require('tailwindcss/colors');

module.exports = {
  content: [
    './renderer/pages/**/*.{js,ts,jsx,tsx}',
    './renderer/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    colors: {
      // use colors only specified
      white: colors.white,
      gray: colors.gray,
      blue: colors.blue,
    },
    extend: {},
  },
  plugins: [],
};
```

**styles/globals.css**

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  body {
    @apply bg-gray-900 text-white;
  }
}

@layer components {
  .btn-blue {
    @apply text-white font-bold px-4 py-2 rounded bg-blue-600 hover:bg-blue-500;
  }
}
```
