### ISSUE TITLE
Support for Next.js 12

### ISSUE THREAD

**Issue by lyorb** [saltyshiomix/nextron#211]
Hi,

Do you plan to support Next.js 12 ?

When updating Next.js I get this error message : `TypeError: Cannot set property 'incremental' of undefined`

Thanks

**Comment by dzcpy** [comment]
Would really like nextron to support Nest.12!

**Comment by thinkclay** [comment]
I was able to upgrade to next 12 without a problem. 

Update your `renderer/tsconfig.json` with the incremental compiler option and that'll probably make your error go away.

```
{
  "extends": "../tsconfig.json",
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ],
  "compilerOptions": {
    "incremental": true
  }
}
```

**Comment by lyorb** [comment]
Indeed, with version 12.0.4 the incremental compiler option automatically updates the `tsconfig.json` file and Nextron therefore supports Nextjs 12 !

**Comment by ianchanning** [comment]
@lyorb It would be useful if you updated the readme to make it clear that Next.js 12 is supported

**Comment by saltyshiomix** [comment]
@lyorb @dzcpy @thinkclay @ianchanning 

Sorry for late reply.

Nextron v8 is out which supports Next.js v12 👍
