### ISSUE TITLE
How can I run MongoDB Realm on the renderer? 

### ISSUE THREAD

**Issue by wawila** [saltyshiomix/nextron#212]
I am trying to run [realm](https://www.npmjs.com/package/realm) on the renderer of my project but I have not been able to make it work correctly. It works perfectly on the main. 

I created my project with the **with-typescript-material-ui** template. I followed [this](https://docs.mongodb.com/realm/sdk/node/integrations/electron-cra/) tutorial and [this](https://github.com/mongodb-university/realm-electron-advanced-quickstart) example. From the tutorial all I got was to modify the [externals from the webpack config](https://docs.mongodb.com/realm/sdk/node/integrations/electron-cra/#create-a-craco-configuration-file) with the difference that I modified the next.config.js on the renderer and did not use CRACO. 

Which leads to my two cases:

1. Including the Node Externals on the webpack config
In this case the project "works"; realm itself run without any issue but the renderer breaks. I get: 
![image](https://user-images.githubusercontent.com/7535177/139067539-8b68ff93-82a9-4998-94aa-b772d029c2af.png)
Which cause my renderer to rerun for every warning, I am assuming that I am excluding something with the Node Externals but have not been able to identify it (I am relatively new to this).  

2. Not including Node Externals on the webpack config
In this case it does not work at all. The renderer breaks completely and throws this error: 
![image](https://user-images.githubusercontent.com/7535177/139068632-44519014-2b73-483b-aef6-84ca78293fff.png)

I am at a loss to what to do to fix this. If anyone can point me in the right direction would be great. 

Here is my next.config.js and package.json:
![image](https://user-images.githubusercontent.com/7535177/139075555-edf98782-a1fd-49a6-a57c-fe665f790b23.png)
![image](https://user-images.githubusercontent.com/7535177/139076068-9db4356d-379e-496c-93f2-56a77f0e00e1.png)

From what I gathered the line that breaks everything is : `const realm = new Realm(CONFIG)`

**Comment by marcomrdagsasc** [comment]
Hello! Did you find out how to do this, or does anybody know about it? Thanks in advance!

**Comment by wawila** [comment]
> Hello! Did you find out how to do this, or does anybody know about it? Thanks in advance!

Hey, sorry for the late response. It has been a while since I last  touched the project involving this. I don't remember everything I did but I remember I had to do something with the Realm configurations. 

Main: 
`this.realm = await Realm.open({path: path, schema: schemas, sync: syncConfig, })
`

Renderer:
`this.realm = await Realm.open({path: path, schema: schemas, sync: true, })`
			
You have to make sure both of the paths are the same and that the open in the main runs first. I think setting sync as true gave me a type error but it work. Don't know if they have changed that. I don't remember if there was anything else. I hope it helps.

**Comment by L-U-C-K-Y** [comment]
@wawila @marcomrdagsasc thanks for your posts, I'm also trying to get nextron working with realm.

Would you mind sharing me your next.config.js and the place where you init the realm db?

I get a lot of different errors...

**Comment by piyawong** [comment]
@L-U-C-K-Y 
hi this is my config its work for me

config.externals = [
        ...config.externals,
        nodeExternals({
          allowlist: [
            /@swc\/helpers/,
            /@babel\/runtime/,

            /antd/,
            /@ant-design\/icons/,

            /rc/,
            /webpack(\/.*)?/,
            'electron-devtools-installer',
          ],
        }),
      ];
