### ISSUE TITLE
getServerSideProps Export Error

### ISSUE THREAD

**Issue by Hulxv** [saltyshiomix/nextron#213]
When I try use getServerSideProps I got this error build:
```
Error occurred prerendering page "/[interval]". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Error for page /[interval]: pages with `getServerSideProps` can not be exported. See more info here: https://nextjs.org/docs/messages/gssp-export
    at /home/mohamed/Desktop/vnstat-client/node_modules/next/dist/export/worker.js:227:27
    at async Span.traceAsyncFn (/home/mohamed/Desktop/vnstat-client/node_modules/next/dist/telemetry/trace/trace.js:60:20)
info  - Exporting (2/2)
Error: Export encountered errors on following paths:
        /[interval]
    at /home/mohamed/Desktop/vnstat-client/node_modules/next/dist/export/index.js:487:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/home/mohamed/Desktop/vnstat-client/node_modules/next/dist/telemetry/trace/trace.js:60:20)


Cannot build electron packages:
Error: Command failed with exit code 1: next export -o /home/mohamed/Desktop/vnstat-client/app /home/mohamed/Desktop/vnstat-client/renderer
```
I went to **https://nextjs.org/docs/messages/gssp-export** and I found that solution
![Screenshot_20211031_004046](https://user-images.githubusercontent.com/73320969/139560406-c2a97aa0-70ea-425c-bb43-5f5797610a62.png)

But how can do that in nextron ?

scripts in package.json:
```json
"scripts": {
    "dev": "nextron --port 12999",
    "build": "nextron build --linux",
    "postinstall": "electron-builder install-app-deps"
},
```

**Comment by Rohithgilla12** [comment]
@Hulxv Hey did you find any hack or workaround to this?
Thanks

**Comment by milton-producercloud** [comment]
@Hulxv could you elaborate a bit your last answer?

**Comment by Hulxv** [comment]
> @Hulxv could you elaborate a bit your last answer? 

In electron js, there's a way to communicate between the main process and renderer process.
It's an inter-process communication.
You can send data from/to the main process to/from the renderer and make actions or events.
You can learn all of that from electron js documentation

**Comment by milton-producercloud** [comment]
Hi @Hulxv . Thanks for your quick reply! 
My main concern here is the following: I _thought_ that Nextron will behave like Next.js in terms of, for instance, revalidating the content of the pages each X minutes, but now it seems to me that once the build is done, pages will be exactly the same unless the user gets another build of the app. Is this correct? 
Thanks again.

**Comment by Hulxv** [comment]
> Hi @Hulxv . Thanks for your quick reply! 
> My main concern here is the following: I _thought_ that Nextron will behave like Next.js in terms of, for instance, revalidating the content of the pages each X minutes, but now it seems to me that once the build is done, pages will be exactly the same unless the user gets another build of the app. Is this correct? 
> Thanks again. 

Sorry for late response.
Yes, that's correct.
Nextron just export nextjs pages on build time. So, you need update your app everytime when you change your page content (or renderer code).

**Comment by milton-producercloud** [comment]
Thank you both!
