### ISSUE TITLE
Workers?

### ISSUE THREAD

**Issue by danikaze** [saltyshiomix/nextron#22]
I'm trying to use web workers with nextron (+typescript), but I haven't found any easy way yet.

I tried installing [@zeit/next-workers](https://github.com/zeit/next-plugins/tree/master/packages/next-workers) and [worker-loader](https://github.com/webpack-contrib/worker-loader).
Also, needed to set some global typings as explained in the webpack configuration ([_Integrating with TypeScript_](https://github.com/webpack-contrib/worker-loader#integrating-with-typescript)):
```ts
// typings/custom.d.ts
declare module 'worker-loader!*' {
  class WebpackWorker extends Worker {
    constructor();
  }

  export default WebpackWorker;
}
```

Trying to include the worker...
```ts
import TestWorker from 'worker-loader!../../test.worker';

//...

const worker = new TestWorker();
worker.postMessage({ foo: 'bar' });
worker.addEventListener('message', (event) => console.log(event));
```

compiles ok, but when trying to execute that code, it results in a 404
```
GET http://localhost:8888/_next/c00177f2ed8cf0fa8620.worker.js 404 (Not Found)
```

Funny thing here is, getting into the `.next` directory, I can see it...
```
$ ls nextron/renderer/.next/c00177f2ed8cf0fa8620.worker.js
c00177f2ed8cf0fa8620.worker.js
```

I can keep trying and if I manage anything, open a PR adding an example on how to use workers but, any ideas on this problem?

**Comment by saltyshiomix** [comment]
@danikaze 

I added a support for web workers 👍 

```bash
# install latest nextron
$ npm install --global nextron@latest

# init your app
$ nextron init my-app --template web-worker

# use it
$ cd my-app
$ yarn && yarn dev
```

**Comment by saltyshiomix** [comment]
@danikaze 

I don't know why, but [@zeit/next-workers](https://github.com/zeit/next-plugins/tree/master/packages/next-workers) has a bug.

I tried so many times and read the README of next-workers, but I could not solve the problem.
BUT, I read the source code and copied and pasted like this:

```js
// in the next.config.js
module.exports = {
  webpack: config => {
    config.target = 'electron-renderer'

    config.module.rules.push({
      test: /\.worker\.js$/,
      loader: 'worker-loader',
      options: {
        name: 'static/[hash].worker.js',
        publicPath: '/_next/'
      }
    })

    config.output.globalObject = `(typeof self !== 'undefined' ? self : this)`

    return config
  }
}
```

Solve the problem.

I could not find the solution, so I didn't send a PR ;(

**Comment by saltyshiomix** [comment]
Nextron now supports web workers, so closed this issue.
