### ISSUE TITLE
Sass/Scss Webpack config

### ISSUE THREAD

**Issue by HeikoMueller** [saltyshiomix/nextron#220]
I am struggling with getting .scss file import to work. I tried adding loader config in next.config.js inside render folder in the usual way I do it in NextJS, and I tried to put this config in nextron.config.js as well. Either way, I had no success. Can you provide an example of how to achieve this?

**Comment by SivertGullbergHansen** [comment]
I see no answer has been given to this issue, so I'd like to give an answer to what solved this issue for me.

I attempted to style my titlebar-component, placing it as a sibling to the `<Main />` tag in my `_document.tsx` file and the selector classname worked but no style would apply. [Once I checked out how to properly reuse components in my app it solved my issue.](https://nextjs.org/docs/basic-features/layouts) 

Basically just create a Layout component-wrapper and add it to your `_app.tsx`. Don't place anything that needs module-styling in the `_document.tsx` file as module-styles are not loaded outside the `<Main />` tag.

Here's an example:
*components/layout/Layout.tsx*
```jsx
import Titlebar from "../titlebar/Titlebar";

export default function Layout({ children }) {
  return (
    <div className='rounded-lg bg-base-100 w-screen h-screen overflow-hidden'>
      <Titlebar />
      <main>{children}</main>
    </div>
  )
}
```

*_app.tsx*
```jsx
import '../styles/globals.scss';
import { AppProps } from 'next/app';
import Layout from '../components/layout/Layout';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Layout>
      <Component {...pageProps} />
    </Layout>
)}

```
