### ISSUE TITLE
feature: upgrade to yarn v2

### ISSUE THREAD

**Issue by tiziodcaio** [saltyshiomix/nextron#221]
If you are intersted, I could make a PR for you.

**Comment by saltyshiomix** [comment]
@tiziodcaio 

Sorry for late reply.

Any PRs are welcome to improve nextron :)
Thank you so much in advance 🙏

**Comment by tiziodcaio** [comment]
I'm sorry but now I'm seeing the program there would be some complications with the installation, so I suggest for the moment to leave as it is.
