### ISSUE TITLE
Error when yarn install

### ISSUE THREAD

**Issue by mustafaabobakr** [saltyshiomix/nextron#222]
win: 10
node: 14.18.2

  ```json
  "dependencies": {
    "electron-serve": "^1.1.0",
    "electron-store": "^8.0.1"
  },
  "devDependencies": {
    "@material-ui/core": "^4.12.3",
    "@types/node": "^14.14.31",
    "@types/react": "^16.9.49",
    "electron": "^15.0.0",
    "electron-builder": "^22.11.7",
    "next": "^11.1.2",
    "nextron": "^7.1.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "typescript": "^4.4.3"
  },
  "volta": {
    "node": "14.18.2",
    "yarn": "1.22.4"
  },
  "build": {
    "buildDependenciesFromSource": true
  }
```

![image](https://user-images.githubusercontent.com/27288406/144189046-0277727b-06d3-4c4d-97e8-c410c593d957.png)

**Comment by mustafaabobakr** [comment]
version 20.28.4 to temporarily resolve the issue.

https://github.com/electron-userland/electron-builder/issues/4157#issuecomment-522933416

**Comment by saltyshiomix** [comment]
@mustafaabobakr 

Sorry for late reply, and thank you for your big efforts 🚀 

Feel free to reopen the issue if any troubles 🙏
