### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by kaaax0815** [saltyshiomix/nextron#223]
I am currently working on project where I want to use nextron on a raspberry pi 4.
Normal electron 15 works fine on arm, why does this not work?
Is there any possibility nextron gets arm support in the near future?

**Comment by m5x5** [comment]
Hey @kaaax0815, do you mind sharing more details?
What error did it display, or what exactly is going wrong?

**Comment by kaaax0815** [comment]
This is a problem with core electron https://github.com/electron/electron/issues/31885
