### ISSUE TITLE
Consider renaming with-typescript-python to with-typescript-python-api

### ISSUE THREAD

**Issue by yoDon** [saltyshiomix/nextron#23]
The two python examples are fairly different in intent in ways that might be difficult for new visitors to spot given how similar their names are.

The current `with-typescript-python` example is focused on using python to provide long-lasting backend services to the electron processes. The current `with-python` example is focused on using python to perform one-off processing tasks. Each has value but the use cases are quite different. By renaming the current `with-typescript-python` to `with-typescript-python-api` we would both reduce visitor confusion and allow both use-cases to be available as examples in both languages (typescript and javascript).

I'm happy to do the renaming work and send a PR if you like the suggestion.

**Comment by saltyshiomix** [comment]
@yoDon 

Sorry for being late replying your suggestion.
I'd be happy if you send me a PR ❤️

**Comment by yoDon** [comment]
I just submitted a PR for the build folder renaming. It would probably merge ok if I did this PR at the same time but for safety I'll hold off on this one until you have time to review and accept the the PR in https://github.com/saltyshiomix/nextron/pull/24 first.

**Comment by saltyshiomix** [comment]
Fully tested and merged #26 ❤️

**Comment by saltyshiomix** [comment]
@yoDon 

Just published `nextron@4.3.0` including #26 👍

**Comment by saltyshiomix** [comment]
@yoDon 

Just published `nextron@4.4.2` including #27 👍

**Comment by yoDon** [comment]
Super!
