### ISSUE TITLE
Nextron does not appear to like namespaces

### ISSUE THREAD

**Issue by newtykins** [saltyshiomix/nextron#236]
![image](https://user-images.githubusercontent.com/19301186/150597646-ca0c823a-7974-4fef-a498-9d8e07bd1b6a.png)

I believe the problem causing this is the fact I have declared types under the Server namespace, and Nextron's webpack configuration does not support this for whatever reason - is this a problem we can tackle?

**Comment by AlexisPiquet** [comment]
Coul you expose the full file ?
