### ISSUE TITLE
How do i integrate jquery

### ISSUE THREAD

**Issue by phemieny7** [saltyshiomix/nextron#237]
I have some jquery plugin i will like to work with, but i haven't be able to integrate jquery. how do i go about it

**Comment by AlexisPiquet** [comment]
Have you tried to added it in the _document.jsx/tsx file?

**Comment by AlexisPiquet** [comment]
Is it solved @phemieny7?

**Comment by phemieny7** [comment]
Not yet

**Comment by AlexisPiquet** [comment]
Which jquery plugin do you want use, where and how?
Could you add a failed example to have more context of use case?

**Comment by phemieny7** [comment]
it now working, thanks

**Comment by saltyshiomix** [comment]
@alexis-piquet 
Thank you for your big efforts and kindness!

@phemieny7 
Feel free to reopen the issue if any troubles.
