### ISSUE TITLE
Consider renaming build folder to nextron

### ISSUE THREAD

**Issue by yoDon** [saltyshiomix/nextron#24]
From what I've seen, the React ecosystem commonly uses a top level `build` folder as an output folder name as a result of the hinting and tool chains used with create-react-app. Nextron is build around Next.js rather than create-react-app, but many React developers move back and forth between next and cra projects, and the current nextron build folder naming convention confuses those efforts. Renaming the current `build` folder to `nextron` would also have the side effect of providing better branding and developer awareness on nextron projects, hopefully increasing use and awareness of nextron on new projects.

I'm happy to submit a PR if you think this sounds like an idea worth considering.

**Comment by saltyshiomix** [comment]
@yoDon 

Your suggestion is so perfect 👍 
I'm busy at work but I'm looking forward to your PR ❤️

**Comment by saltyshiomix** [comment]
I just updated `nextron@4.1.2` for maintenance dependencies :)

**Comment by yoDon** [comment]
I think this is ok to close now :)

**Comment by saltyshiomix** [comment]
@yoDon 

Thank you very much!!
