### ISSUE TITLE
Nextron support SSR?

### ISSUE THREAD

**Issue by stegano** [saltyshiomix/nextron#240]
It seems that dynamic data is not reflected(data at the time of build is included) in `PageComponent.getInitialProps` when production build with Nextron

Can I use SSR at the time the page is executed rather than at build time?

example code
```ts
// home.tsx
const Home = ({timestamp}) => {
  // ...
  return <div>{timestamp}</div>
}

Home.getInitialProps = () => ({timestamp: Date.now()}); // Server Side Rendering Code

export default Home;
```

**Comment by saltyshiomix** [comment]
@stegano 

Sorry for late reply.

Nextron does not support SSR, because electron in production mode can handle only static files.

So we cannot use:
- API routes
- getInitialProps
- getServerSideProps
- and so on... (which use server side features)

Feel free to reopen the issue if any troubles :)

**Comment by lacymorrow** [comment]
Yeah, nextron is already using prerendered pages
