### ISSUE TITLE
tailwindcss classes do not work in the example with-typescript-tailwindcss

### ISSUE THREAD

**Issue by NotPratyush** [saltyshiomix/nextron#243]
When you are using tailwindcss with the example, the classes do not work properly.
```
*file structure*
----------------
renderer
    |_tailwind.config.js
    |_postcss.config.js
package.json
```

# How to reproduce
Run the example `with-typescript-tailwindcss` (https://github.com/saltyshiomix/nextron/examples/with-typescript-tailwindcss)

# What I cannot do:
Cannot use custom colors, classes and `@rules` with tailwindcss and some default class like `bg-black`

# What is actually happening
When i first went to `localhost:{port}/{page}` to see if the background class was applied or not. I could not see a colorful background. I checked my Nextron app and it, too, did not have the colorful background.

## For instance
This is how my Nextron app looks like

![Untitled](https://user-images.githubusercontent.com/96735079/158185943-f7450ad8-96ba-46c3-8287-b62eca8144c4.jpg)

Apply the `bg-{color}` class with any color (except for white, which is already there), you will notice that the color does not change, it still looks like this.

![Untitled](https://user-images.githubusercontent.com/96735079/158185943-f7450ad8-96ba-46c3-8287-b62eca8144c4.jpg)

I cannot figure out why this is happening, if someone has any idea, please let me know.
My Discord tag is Pratyush#2950 (feel free to DM me anytime)

# Support needed

**Comment by TimotiusAnrez** [comment]
move both tailwind config and post css to root directory to get it working

**Comment by saltyshiomix** [comment]
@NotPratyush CC: @arunavo4 

Sorry for late reply.

Just updated tailwindcss examples (bump v2 => v3), and the custom class works fine 👍 

**postcss.config.js**

```js
module.exports = {
  plugins: {
    tailwindcss: {
      config: './renderer/tailwind.config.js',
    },
    autoprefixer: {},
  },
};
```

**tailwind.config.js**

```js
const colors = require('tailwindcss/colors');

module.exports = {
  content: [
    './renderer/pages/**/*.{js,ts,jsx,tsx}',
    './renderer/components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    colors: {
      // use colors only specified
      white: colors.white,
      gray: colors.gray,
      blue: colors.blue,
    },
    extend: {},
  },
  plugins: [],
};
```

**styles/globals.css**

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  body {
    @apply bg-gray-900 text-white;
  }
}

@layer components {
  .btn-blue {
    @apply text-white font-bold px-4 py-2 rounded bg-blue-600 hover:bg-blue-500;
  }
}
```
