### ISSUE TITLE
Want to be a collaborator?

### ISSUE THREAD

**Issue by saltyshiomix** [saltyshiomix/nextron#25]
I'll keep on meintenancing, but I think it's better to be more open :)

Any ideas?

Please feel free to comment and raise your hands for nextron 👍

**Comment by saltyshiomix** [comment]
My offer for @yoDon , @ColeTownsend :)

**Comment by yoDon** [comment]
Hi @saltyshiomix - thank you so much, I am honored. For the moment I think my contributions are likely to be sparse enough and irregular enough that I for now I should stay at this level, as a fan and contributor :)

**Comment by lacymorrow** [comment]
I may be interested, I can't contribute often but potentially small quality-of-life changes. Also happy to code-review any PRs.

**Comment by saltyshiomix** [comment]
@lacymorrow 

I'll add you to the collaborators later today 👍

**Comment by saltyshiomix** [comment]
Added @lacymorrow 

See the invitation via https://github.com/saltyshiomix/nextron/invitations

**Comment by lacymorrow** [comment]
Thanks @saltyshiomix, I'll PR any changes I make.

Please feel free to bug me anytime 😄

**Comment by Psycokwet** [comment]
Hello ! I'm just starting with nextron but I love it, I would love to be a contributor as soon as I am able too.

**Comment by saltyshiomix** [comment]
Added @Psycokwet :)

**Comment by Psycokwet** [comment]
Thank you ! I hope we will do great things together !

**Comment by saltyshiomix** [comment]
Move to: [Looking for maintainers ⚡ #244](https://github.com/saltyshiomix/nextron/discussions/244)

**Comment by usmangurowa** [comment]
Hi, i am not sure if you are still looking for contributors, but I will be happy to be one. I came across Nextron just yesterday, and I must say, I love how easy and straightforward it is. I will love to contribute and bring new features, starting by creating a nextron app example with mantine UI.
