### ISSUE TITLE
Example with preload.js and IPC bridge

### ISSUE THREAD

**Issue by niteshbalusu11** [saltyshiomix/nextron#259]
Hello! 

Looks like nodeIntegration:true is default on Nextron,could you please post an example to communicate with main process without nodeIntegration (the electron IPC bridge way) along with the files that have to be changed to get it to work. 

I have looked at this post but couldn't get it to work. Seems like it's an old one. 

https://github.com/saltyshiomix/nextron/issues/39

Also, thank you for this wonderful project, I have looked at a few libraries for building my app on electron and nextron turned out to be the most easy to use. Massively underrated.

**Comment by SlimShadyIAm** [comment]
Second this, cannot figure this out.

**Comment by niteshbalusu11** [comment]
> Second this, cannot figure this out.

I figured this one out.

In the root of the project, create a file called `nextron.config.js` if its not already present. Add this code.

```
module.exports = {
  webpack: (defaultConfig, env) =>
    Object.assign(defaultConfig, {
      entry: {
        background: './main/background.ts',
        preload: './main/preload.ts',
      },
    }),
};
```

In your renderer directory, there should be a `next.config.js`, change it to this:

```
module.exports = {
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.target = 'electron-renderer';
      config.node = {
        __dirname: true,
      };
    }
    config.output.globalObject = 'this';
    return config;
  },
};
```

Then in your `create-window.js` file you can modify this part to turn off nodeintegration and turn on context isolation.

```
  const browserOptions: BrowserWindowConstructorOptions = {
    ...options,
    ...state,
    webPreferences: {
      preload: path.join(__dirname, '../app/preload.js'),
      nodeIntegration: false,
      contextIsolation: true,
      ...options.webPreferences,
    },
  };
```

After that you can create a `preload.js` file in the main folder. 

After that you can just follow electrons documentation of IPC Communication to build your project.
https://www.electronjs.org/docs/latest/tutorial/ipc

**Comment by niteshbalusu11** [comment]
If you're using typescript, then use typescript files in `background` and `entry` in `nextron.config.js` file.
And `preload.js` would be `preload.ts`.
Everything else would be regular js files.

**Comment by WynterJones** [comment]
> > Second this, cannot figure this out.
> 
> I figured this one out.
> 

Thank you for figuring this out :)

**Comment by chriszrc** [comment]
@niteshbalusu11 Is there a working example repo of  this somewhere? I followed all the steps, but I get "cannot find "module"", I'm guessing there's a webpack error somewhere?

**Comment by SimonFrank14** [comment]
Hi, I faced similar issues:

## Require is not defined
First I encountered a "require is not defined" error from Recoil Root. This could be fixed by changing the following line to my `next.config.js`.

```js
config.target = 'web'
```

Originally there was a 
```js
config.target = 'electron-renderer'
```

This setting is - according to my research - no longer needed with Electron 13


## Module is not defined
Secondly, I faced a similar issue as @chriszrc. The console threw `module is not defined`. I could fixed this issue by adding `sandbox: false` to my browser window in the `create-window.(js|ts)` file:

~~~js
...

const browserOptions: BrowserWindowConstructorOptions = {
		...state,
		...options,
		webPreferences: {
			preload: path.join(__dirname, 'preload.js'),
			nodeIntegration: false,
			contextIsolation: true,
			sandbox: false,
			...options.webPreferences,
		},
	};
~~~
