### ISSUE TITLE
Nextron with next-auth

### ISSUE THREAD

**Issue by amaranzero** [saltyshiomix/nextron#264]
Someone knows how to configure nextron with next-auth? 
When i build then app next-auth give me the error 

```
GET app://./api/auth/session net::ERR_FILE_NOT_FOUND
[next-auth][error][client_use_session_error] 
https://next-auth.js.org/errors#client_use_session_error TypeError: Failed to execute 'sendBeacon' on 'Navigator': Beacons are only supported over HTTP(S)
Uncaught (in promise) TypeError: Failed to execute 'sendBeacon' on 'Navigator': Beacons are only supported over HTTP(S).
```

And i don't find anything in docs

**Comment by m5x5** [comment]
Hello @amaranzero, thanks for opening the issue.
Unfortunately it is not possible to use SSR in production in Nextron.
[Here](https://auth0.com/blog/securing-electron-applications-with-openid-connect-and-oauth-2/) is an approach for how to get authentication working without SSR using Auth0.

**Comment by amaranzero** [comment]
> Hello @amaranzero, thanks for opening the issue. Unfortunately it is not possible to use SSR in production in Nextron. [Here](https://auth0.com/blog/securing-electron-applications-with-openid-connect-and-oauth-2/) is an approach for how to get authentication working without SSR using Auth0.

Thank you for the information.
