### ISSUE TITLE
Cannot see my app after build

### ISSUE THREAD

**Issue by mikehenriquezf** [saltyshiomix/nextron#265]
Im using the Nextron with Typescript template to build a application. Im running yarn build to create my production build, but when i launch the DMG file i can only see the app name in the title bar, and no window is launched, i cannot see developers tools either. Any idea on what im doing wrong?

**Comment by niteshbalusu11** [comment]
Production version won't launch devtools. In background.js there is a check to make sure it launches only in dev mode with yarn dev command.

**Comment by ahmedsaheed** [comment]
@saltyshiomix any idea what's happening here ?

**Comment by ahmedsaheed** [comment]
hi @mikehenriquezf you'd have to specify the `dist` directory in your `package.json`

Like so: 

```json
"directories": {
      "output": "dist",
      "buildResources": "resources"
    }

```
