### ISSUE TITLE
How to show a window from a page by use ipcRenderer?

### ISSUE THREAD

**Issue by letruonglamit** [saltyshiomix/nextron#269]
When I implement, I got the errors like this:
![Screen Shot 2022-07-27 at 10 50 33](https://user-images.githubusercontent.com/22797715/181156866-f139a173-a9c5-4ef3-bdb8-5e1caf763fc4.png)

**Comment by Psycokwet** [comment]
If you comment line 29, does the error happen?
It seem to come from elsewhere

**Comment by roscoevanderboom** [comment]
@letruonglamit I tried to recreate your error using the Material UI template but it works fine for me. Make sure nodeIntergration: true, 
contextIsolation: false, 
and if all that fails, try 
window.electron.ipcRenderer.send("sss").

**Comment by bm777** [comment]
@letruonglamit, you should load it dynamically.

Something like this:

```js
let ipcRenderer

if(typeof window !== "undefined" && window.process && window.process.type === "renderer"){
    ipcRenderer = window.require('electron').ipcRenderer
    console.log("DEBUG: ipcRenderer", ipcRenderer)
    ipcRenderer.send("sss")
}
```

**Comment by bm777** [comment]
Will close this issue :), feel free to reopen it if you have other issues.
