### ISSUE TITLE
Nextron does not work with Tailwind 3

### ISSUE THREAD

**Issue by milanmdev** [saltyshiomix/nextron#275]
Whenever I try and use Tailwind 3, it doesn't seem to render properly. The page is broken and none of the styles load.

Nextron version: 8.1.0
Next version: 12.2.5
Tailwind version: 3.1.8

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/29466935/185769499-ec5685b5-8b4c-433c-b38c-26afe1210690.png">

**Comment by SpiritLetsPlays** [comment]
Hey, did you manage to fix this? @milanmdev 
Currently having the same issue
