### ISSUE TITLE
Build of the typescript example that fails

### ISSUE THREAD

**Issue by Achaak** [saltyshiomix/nextron#278]
Hello,

When I wanted to debug my app I tried to test the template for typescript whis `pnpx create-nextron-app my-app --example with-typescript`
However, it was impossible to launch the build.

Indeed, at first I had an error indicating that the @babel/runtime-corejs3 module was missing whe, I run whis dev
![image](https://user-images.githubusercontent.com/39270779/187759903-9624ac4e-3d21-4f40-a50c-adda14200938.png)
And when I try to build
![image](https://user-images.githubusercontent.com/39270779/187760363-a4ee82ed-f671-456b-bb76-d10297faeefe.png)

After adding it I tested the dev command and no problem
However, when I wanted to build the project I got this error :
![image](https://user-images.githubusercontent.com/39270779/187760533-2a187ca2-ca35-4c90-8edd-fd9d98b971b1.png)

I specify that apart from the addition of the module, the project is blank.

OS: windows
Run with pnpm

**Comment by xithalius** [comment]
Have the same problem on a fresh project using the with-typescript-tailwindcss example and installing using pnpm. Switched to using npm for now.

**Comment by saltyshiomix** [comment]
@Achaak @xithalius 

Sorry for late reply.

As mentioned in README, we can build nextron with `--shamefully-hoist` option:

https://github.com/saltyshiomix/nextron/tree/12052446de50d8c7b0733a029d63ac1e1e77499e/examples/with-javascript#install-dependencies

Or we can set `.npmrc` and `pnpm install && pnpm build` work:

**.npmrc**

```
node-linker=hoisted
```

See https://github.com/pnpm/pnpm/issues/3415#issuecomment-1042428327 for more information.
