### ISSUE TITLE
.

### ISSUE THREAD

**Issue by dxdns** [saltyshiomix/nextron#285]

**Comment by ravi-sohal** [comment]
I am having the same issue - ERR_CONNECTION_REFUSED

**Comment by saltyshiomix** [comment]
@dxdns @ravi-sohal 

Sorry for late reply and thank you for your issue.

Electron is not normal Node.js server. This means we can use electron as if it is like a node.js server when development mode, but actually Electron can handle only static files when production mode. So, we can't use debugging 8888 port when production.
