### ISSUE TITLE
Electron app with multiple browser window not showing on menu bar Macos

### ISSUE THREAD

**Issue by han-see** [saltyshiomix/nextron#298]
Hi, 

I have a problem with my current application that's running on macos. Since I created one extra browser window from the background.ts, I cannot see the menu bar of my electron app. When I do cmd + tab, there is also no electron app icon showing.
My electron app is running just fine, I can also see it running in the activity monitor.

I build my background.ts similar to the one in this example https://github.com/lacymorrow/nextron-worker-process/blob/master/main/background.js

I'm running nextron 8.2.0 on macos 13.0.1

Does anyone also have the same problem?

**Comment by alexis-piquet** [comment]
Hey @han-see.
Do you have any reason to create a secondary windows? If I remember well, I've encouter the same issue with one of my apps protected by Auth0 authetication. If I've no refresh token and no Profile I create a Auth window, if I've those informations I create a App windows, you can't have to browser window in parallel.

To have more context of my use case here you can find how I've implemented it:

``` typescript
import { MODEL_AUTH0, PROFILE, SERVICE_AUTH0, SERVICE_MONGODB } from '@constants'
import { initialize } from '@electron/remote/main'
import Services from '@server/services'
import { initRoles } from '@server/statics/roles'
import createAuthWindow from '@server/window/auth'
import createAppWindow from '@server/window/client'
import { mongoose } from '@typegoose/typegoose'
import Debug from 'debug'
import { app } from 'electron'
import serve from 'electron-serve'

const debug = Debug('init')
const { MONGODB_URI, NODE_ENV } = process.env
const isProd = NODE_ENV === 'production'

if (isProd) {
	serve({ directory: 'app' })
} else {
	app.setPath('userData', `${app.getPath('userData')}-developement`)
}

(async (): Promise<void> => {
	await Promise.all([
		initialize(),
		app.whenReady,
		mongoConnect(),
		startApplication()
	])
})()

async function mongoConnect() {
	if (!MONGODB_URI) return debug('Error: [ %s ] MONGODB_URI not defined', SERVICE_MONGODB)
	try {
		await mongoose.connect(MONGODB_URI)
		debug('[ mongoConnect ] [ Connected ] to mongodb database')
    
	} catch (error) {
		debug('[ mongoConnect ] [ Error ]: [ %s ] %o', SERVICE_MONGODB, error)
	}
}

async function startApplication() {
	try {
		await initRoles()
		const access = await Services[SERVICE_AUTH0][MODEL_AUTH0].refreshTokens()
		debug('[ startApplication ] [ access ] %o', access)
		const profile = await Services[SERVICE_MONGODB][PROFILE].getProfile(access.profile)
		debug('[ startApplication ] [ profile ] %o', profile)
		if (!access && !profile) {
			return createAuthWindow()
		}
		return createAppWindow()
	} catch (error) {
		debug('Error: %o', error)
		return createAuthWindow()
	}
}

app.on('window-all-closed', app.quit)
```

**Comment by han-see** [comment]
Hi @alexis-piquet, 

I created the second window to create a notification widget. I already fix this issue but forgot to post it here.
I fixed it by calling app.dock.show() after the creation of the second window. 

Thank you for your reply nevertheless :)
