### ISSUE TITLE
Blank page with Electron 22.0.0, in dev mode, but renders fine on Electron 21.3.3 (20.x too)

### ISSUE THREAD

**Issue by Taarek** [saltyshiomix/nextron#299]
I updated Electron to 22.0.0 to avoid all these vulnerabilities reports (`minimatch` and `got`).

But for some reason in development build(npm run dev) the page is completely blank, there are no errors in both the nodejs console and the browser console. In a production build, it renders just fine

On Electron 21.3.3, it works fine in both dev and prod builds, just that npm complains about `Got` having a vuln.

As you can see here, the page is clearly being loaded, just nothing shows up.
![image](https://user-images.githubusercontent.com/13603398/205035806-6c09991a-f6dd-42c2-bc34-e26cf819c671.png)

I've been trying to figure this out for a few hours now and p much close to giving up. 😅, so I'd appreciate any replies ❤️

Edit, I just noticed for some reason NextJS/Nextron inserts this inside <head> during dev build.
Removing it under the elements tab makes things start showing up, why would this happen exclusively on Electron 22? 
```html
<style data-next-hide-fouc="true">body{display:none}</style>
```

Second edit:
This seems to be caused by the next.config.js that's included in the example:
![image](https://user-images.githubusercontent.com/13603398/205283080-de353271-e731-4ea6-a7cb-f205c8645880.png)
It seems like isServer is true/false in the same "order" as a production build. Electron 21.3.3 does not behave this way.
See this table for reference:

This is debug build on Electron 22.0.0:
| Electron Version | isServer |
| ------------- | ------------- |
| 22.0.0  | false  |
| 22.0.0  | true  |
| 22.0.0  | true  |

This is prod build on Electron 22.0.0:
| Electron Version | isServer |
| ------------- | ------------- |
| 22.0.0  | false  |
| 22.0.0  | true  |
| 22.0.0  | true  |

This is debug build on Electron 21.3.3:
| Electron Version | isServer |
| ------------- | ------------- |
| 21.3.3  | true |
| 21.3.3  | false  |
| 21.3.3  | true  |

This is prod build on Electron 21.3.3:
| Electron Version | isServer |
| ------------- | ------------- |
| 21.3.3  | false |
| 21.3.3  | true  |
| 21.3.3  | true  |

See how on Electron 22.0.0, the if statement and `config.target` happens in the same order in both debug and prod builds?
But on Electron 21.3.3, it's not the same, and they're different.. Which is probably why the dev build is misbehaving on Electron 22, and not 21.3.3, it's because Electron 22 gets `config.target` unset after the third iteration, which is not the case on Electron 21.3.3

**Comment by ShahriarKh** [comment]
Does any body have a solution for this?

**Comment by vandetho** [comment]
there is a workaround by adding style `display: block !important` to body

**Comment by tomaszczura** [comment]
Does not work for me

**Comment by KaptinLin** [comment]
electron 24.0.0 is not working too.

**Comment by geraldoramos** [comment]
same with Electron 23

**Comment by irg1008** [comment]
See https://github.com/saltyshiomix/nextron/issues/346

**Comment by saltyshiomix** [comment]
@Taarek CC: @ShahriarKh @vandetho @tomaszczura @KaptinLin @geraldoramos @irg1008 

Sorry for late reply 🙇 

Just remove `config.target = 'electron-renderer'` in `next.config.js`. It works like a charm 🚀 

**Before**

```js
module.exports = {
  trailingSlash: true,
  images: {
    unoptimized: true,
  },
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.target = 'electron-renderer'
    }

    return config
  },
}
```

**After**

```js
/** @type {import('next').NextConfig} */
module.exports = {
  trailingSlash: true,
  images: {
    unoptimized: true,
  },
  webpack: (config) => {
    return config
  },
}
```

**Comment by MaxLiebsch** [comment]
@saltyshiomix I wonder, how you can say it is fixed?

**Comment by tomaszczura** [comment]
@saltyshiomix this is not a fix. I am getting error that node libraries can not be found on next side. The issue should be reopened until it is really fixed
