### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by ultraBlack** [saltyshiomix/nextron#3]
I noticed in https://dev.to/saltyshiomix/build-the-electron--nextjs-app-for-3-steps-5g2p you mentioned hot reloading for both main and renderer processes is todo. I was just wondering how long it might be before that gets implemented?
I thank you. This project really helped me get off the ground!

**Comment by saltyshiomix** [comment]
Thank you @ultraBlack !
I forgot to add support for hot reloading, sorry for inconvenience.

Now `nextron@1.1.0` supports renderer process's hot reloading.

Try these commands:

```bash
# Clear cache (optional)
$ npm uninstall -g nextron

# Install latest nextron
$ npm i -g nextron@latest

# Create `with-javascript-material-ui` project (any choices are ok)
$ nextron init test-app --template with-javascript-material-ui

# Run as a development mode
$ cd test-app
$ npm install
$ npm run dev
```

If you have any ideas or bugs, please contact me anytime!

**Comment by saltyshiomix** [comment]
And, after writing that article, I notice that "hot reloading main process" means "must restart electron process". So it may be difficult to implement it, sorry.

**Comment by ultraBlack** [comment]
Hi,

I tried your instructions with the with-typescript template, but this happened. I am on Windows.

![2018-07-22 00_52_28-electron](https://user-images.githubusercontent.com/9144186/43043485-b356fb20-8d49-11e8-91f6-2ad8c4538b81.png)

**Comment by saltyshiomix** [comment]
Mmm..., my windows 7 doesn't occur that error.

**with-typescript**

![with-typescript](https://user-images.githubusercontent.com/5608079/43045179-a349505c-8dee-11e8-89ac-a0b3b2a07aa1.png)

**with-typescript-material-ui**

![with-typescript-material-ui](https://user-images.githubusercontent.com/5608079/43045190-bdaf086a-8dee-11e8-8fe5-0145dd450cb3.png)

Could you tell me Node.js and npm versions?

I'll test nextron on my another windows (windows 10).

**Comment by saltyshiomix** [comment]
And then, `nextron@1.1.0` contains some bugs, I fixed it `nextron@1.1.2`.

If you have trouble with an error "port 8888 already in use", try these commands:

```
(windows command prompt)
> netstat -ano | findstr 0.0.0.0:8888
> taskkill /pid <YOUR-8888-PORT-PROCESS-ID> /t /f
```

Then, run nextron:

```bash
$ cd test-app
$ npm run dev (or `yarn dev`)
```

**Comment by ultraBlack** [comment]
I'm not sure what fixed it but after updating to nextron@1.1.5, @babel/core@7.0.0-beta.54, electron-builder@20.24.4, and Node.js to 8.11.3 LTS, it works. Using NPM 6.2.0.

**Comment by saltyshiomix** [comment]
Thank you for your reporting that!

This is a minute thing, but please be careful to update or upgrade your dependencies.
Internally `next@6.1.1` uses `@bable/core@7.0.0-beta.42`, and mismatch versions may cause conflicts.
And `electron-builder@latest` often have some bugs.

I'll keep to try implementing whole hot reloading, anyway 👍

**Comment by saltyshiomix** [comment]
Now `nextron@1.2.0` supports hot reloading!
Would you like it?
