### ISSUE TITLE
Male nextron-dev forward extra command line args to electron main process

### ISSUE THREAD

**Issue by bbenoist** [saltyshiomix/nextron#300]
Hi!

If I understand https://github.com/saltyshiomix/nextron/blob/main/lib/nextron-dev.ts#L66 correctly, the `nextron dev` has no ways of forwarding the command-line args to the electron main process.

As I'm developing an app which accepts arguments, It'd help me testing them quicker.

Can we add a `--` command-line separator to make nextron-dev forward every following arg to the main process?

i.e. Support `nextron dev -- ./some-dir --a-specific-flag`

**Comment by saltyshiomix** [comment]
@bbenoist 

Sorry for late reply 🙇 

I just released nextron v8.11.1, which includes electron option configuration.
If you have time, please try new one and let me know how is it going 🙏 

https://github.com/saltyshiomix/nextron#--electron-options-default-undefined

```json
{
  "scripts": {
    "dev": "nextron --electron-options=\"--no-sandbox\""
  }
}
```

**Comment by bbenoist** [comment]
Hi! Sorry @saltyshiomix but I don't use nextron anymore as I've stopped working on the project which relied on it.
Thanks anyway for the answer :)

**Comment by saltyshiomix** [comment]
Hi, @bbenoist !
No problem for it.
Thank you for your trying nextron!
Ok, I close the issue, but feel free to open any issues if any updates or troubles :)
