### ISSUE TITLE
unable to build 

### ISSUE THREAD

**Issue by DanielDoe** [saltyshiomix/nextron#31]
Hey i got an issue when i tried to build my project. I tried to create and new project without my existing codes but still got the same error message. 
![nextron](https://user-images.githubusercontent.com/30290716/57571246-6a615b80-7403-11e9-95d9-bba30e88943a.JPG)
![npmbuild](https://user-images.githubusercontent.com/30290716/57571247-6af9f200-7403-11e9-8fd2-175fb3f093db.JPG)
 I would be very glad to obtain your assistance. Thank you so much.

**Comment by DanielDoe** [comment]
I tired updating my yarn and npm still got the same error.. Tried on macOS had the same exit code 1 error unfortunately i am way done with my codes in the dev mode.. I would be so glad if you could help me... Thank you.

**Comment by saltyshiomix** [comment]
Hi, @DanielDoe !

I tried your repo <https://github.com/DanielDoe/idl_management_next> but I couldn't face your problems.
(`npm run dev` and `npm run build` are working on my macOS.)

It seems to occur an error when to build the renderer process.
Please try to run commands below to investigate your errors:

```bash
$ npx next build renderer
```

**Comment by saltyshiomix** [comment]
@DanielDoe 

Basically, next.js apps have two build process:

- server webpack process
- client webpack process

Be careful to handle client only source codes like below:
(for example, `electron.ipcRenderer` exists only in client webpack process)

```js
export default class extends React.Component {
  // prevent SSR webpacking
  ipcRenderer = electron.ipcRenderer || false;

  state = {
    logo: null,
    ipcResult: 'no ipc messaging',
  };

  onClickWithIpc = () => {
    if (this.ipcRenderer) {
      this.ipcRenderer.send('ping-pong', 'some data from ipcRenderer');
    }
  };

  onClickWithIpcSync = () => {
    if (this.ipcRenderer) {
      this.setState({
        ipcResult: this.ipcRenderer.sendSync('ping-pong-sync', 'some data from ipcRenderer'),
      });
    }
  };

  componentDidMount() {
    this.setState({
      logo: resolveWithIpc('static/logo.png'),
    });

    if (this.ipcRenderer) {
      this.ipcRenderer.on('ping-pong', (event, data) => {
        this.setState({
          ipcResult: data,
        });
      });
    }
  }

  componentWillUnmount() {
    if (this.ipcRenderer) {
      this.ipcRenderer.removeAllListeners('ping-pong');
    }
  }

  render() {
    return (
      <React.Fragment>
        <Head>
          <title>Home - Nextron (ipc-communication)</title>
        </Head>
        <div>
          <p>
            ⚡ Electron + Next.js ⚡ - <LinkWithIpc href="next"><a>Go to next page</a></LinkWithIpc>
          </p>
          <img src={this.state.logo} />
          <hr />
          <button onClick={this.onClickWithIpc}>IPC messaging</button>
          <button onClick={this.onClickWithIpcSync}>IPC messaging (sync)</button>
          <p>{this.state.ipcResult}</p>
        </div>
      </React.Fragment>
    );
  }
};
```

**Comment by saltyshiomix** [comment]
It may be helpful to run `npx next build ./renderer` before run `npm run build` :)

**Comment by DanielDoe** [comment]
You’re a hard man to find but Arigato Nextron Sama
Kami bless you a lot I’ll try it out and give you feed a k soon... I’ll
recommend you close or I close the issue since I could report to you if
anything... I’m so grateful

**Comment by DanielDoe** [comment]
[image: Screenshot 2019-05-13 at 10.22.56 PM.png]

successful... I'm grateful

**Comment by saltyshiomix** [comment]
@DanielDoe 

You're welcome :)
If you have any another troubles, feel free to contact me here 👍
