### ISSUE TITLE
Next 13 app dir

### ISSUE THREAD

**Issue by HoudhaifaNA** [saltyshiomix/nextron#311]
Can we use app dir feature in next v13 ?
When I use it everytime I click on a link it reloads the page.
Also when I upgrade to latest Electron version v22.0.3, it doesn't work

**Comment by cellis** [comment]
The `app` directory is reserved in Next.js 13, but nextron's build uses it. Will have to downgrade to Next.js 12 or parameterize the `app` directory and read it from the config... I want to make a PR but don't have time right now.

**Comment by HoudhaifaNA** [comment]
Actually, it works. I am in development and it works, I hope it will be the same in production.

**Comment by saltyshiomix** [comment]
For production build, we need to run `next export` command for production static files, but currently Next.js does not support `next export` with `app` directory.

See here for more information:

https://beta.nextjs.org/docs/app-directory-roadmap#planned-features

Issues:

- https://github.com/vercel/next.js/issues/43417
- https://github.com/vercel/next.js/issues/42282#issuecomment-1298308932

**Comment by cellis** [comment]
@saltyshiomix is there a possibility to hardcode the `exportMapPath` in next.config.js order to fix this?

**Comment by iancleary** [comment]
@saltyshiomix FYI, with the release of the stable next export command with the app directory, I was able to get both dev and prod to work without changing the nextron configuration.

https://nextjs.org/docs/app/building-your-application/deploying/static-exports

Dev working: https://github.com/iancleary/horizon/issues/10#issuecomment-1546756741

Prod working: https://github.com/iancleary/horizon/issues/10#issuecomment-1546757114


The only thing to note is that the dev and build temporary files share the root app/ folder. If you care to preserve both, that might be an issue for you. I am fine with that as they are both folders that are removed/cleaned in the start of dev mode or the start of a build...so no stale files cross contaminate across dev to prod or from prod to dev.

**Comment by jonstelly** [comment]
For next 13 with App Router, I think the recommended way to generate the equivalent of the deprecated `next export` is to just set `output: export` in the next.config.js, at which point `next build` will spit out the static bundle/build.

I wonder about doing the following:

1. Modify next.config.js and add `output: export` (this is now like `next build && next export`)
2. Modify nextron-build to not call "next export", instead copy the exported-output from step 1 to appdir
3. If the goal of nextron is to support next 13 and previous versions of next, either auto-detect if we're on next 13 or not and still call next export if on <=12?

It also feels like with nextjs app router, `appdir` should probably be something other than `app`?

I can take a stab at a PR for this to get the ball rolling if the above sounds like a good plan

**Comment by remendes** [comment]
How can I make use of this in nextron? When installed, nextron brings Next 12, not 13. Shall I manually upgrade to 13 in package.json? My app is developed using App router - I just need to make it work on Electron...

**Comment by 0xPT** [comment]
@iancleary Seems to work fine until I import "electron" into any files.. Getting this error:

Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath

**Comment by nandorojo** [comment]
Is there a way to use the `standalone` approach instead of `output: export`, where `electron` actually spins up the next server itself and runs it locally?
