### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by HA-SEUNG-JEONG** [saltyshiomix/nextron#312]
![image](https://user-images.githubusercontent.com/88266129/212524089-706ef5b3-0790-4351-a633-dcd190c408e7.png)

and I run `yarn && yarn dev`,

![image](https://user-images.githubusercontent.com/88266129/212524115-27681bd2-558c-407a-9167-e35b85655748.png)

`localhos:8888` not showing...

![image](https://user-images.githubusercontent.com/88266129/212524141-eec76c77-94b9-4667-adff-eb6b31f3c216.png)

**Comment by HoudhaifaNA** [comment]
I think because global doesn't work on the browser, so don't open the project in the browser run yarn dev and it will open a desktop app.

**Comment by HA-SEUNG-JEONG** [comment]
No need to modify the code? Running with `yarn dev` doesn't open it either.

**Comment by HoudhaifaNA** [comment]
Try to delete the project and create it again and try npm instead of yarn because I installed the project yesterday and it worked fine. But don't update electron because it will break

**Comment by saltyshiomix** [comment]
@HA-SEUNG-JEONG 

Could you tell me the version of electron?

**Comment by manuthecoder** [comment]
I am experiencing the same issue - and I followed all the directions on the README file.

**Comment by Ahtisham-01** [comment]
modify the next.config.js:

    if (!isServer) {
      config.target = 'electron-renderer';
      config.node = {
        __dirname: true,
      };
    }

    config.output.globalObject = 'this';

**Comment by alexis-piquet** [comment]
@HA-SEUNG-JEONG, Could you give me more context of your usage? I don't understand why you want to use global.
