### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by Ahtisham-01** [saltyshiomix/nextron#318]
- global is not defined webpack error when we use context isolation 
- How we can fix this error

**Comment by cellis** [comment]
Don't use context isolation ( I agree with the Electron team's rationale for this, IF you EVER plan to load 3rd party websites or even your own website that has 3rd party javascript running, as they could access your IPC calls ). However if you treat the app as a secure app and never load third party websites or scripts, then it's fine to turn off.

If you still want to go ahead, modify the next.config.js:

```webpack: (config, { isServer }) => {
    if (!isServer) {
      config.target = 'electron-renderer';
      config.node = {
        __dirname: true,
      };
    }

    config.output.globalObject = 'this';
    ...
```

**Comment by Ahtisham-01** [comment]
Thanks alot brother

**Comment by saltyshiomix** [comment]
@Ahtisham-01 
Sorry for late reply 🙇 

May be we can remove `config.target = 'electron-renderer'` in `next.config.js`. 

**Before**

```js
module.exports = {
  trailingSlash: true,
  images: {
    unoptimized: true,
  },
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.target = 'electron-renderer'
    }

    return config
  },
}
```

**After**

```js
/** @type {import('next').NextConfig} */
module.exports = {
  trailingSlash: true,
  images: {
    unoptimized: true,
  },
  webpack: (config) => {
    return config
  },
}
```
