### ISSUE TITLE
Build for windows 32bit

### ISSUE THREAD

**Issue by SarkarKurdish** [saltyshiomix/nextron#322]
Hey `nextron build` seems to build for x64 and I can't find any settings to change it, how can I target to windows 32bit?

**Comment by saltyshiomix** [comment]
@SarkarKurdish 

Did you run `nextron build --win --ia32`?

**Comment by SarkarKurdish** [comment]
Thanks it worked, I did not thought I can use electron arguments with nextron.

**Comment by saltyshiomix** [comment]
@SarkarKurdish 

Currently nextron does not support all arguments, but some options are documented in [README](https://github.com/saltyshiomix/nextron#build-options) :)
