### ISSUE TITLE
Building Sqlite3 native dependencies stuck when building for ia32

### ISSUE THREAD

**Issue by SarkarKurdish** [saltyshiomix/nextron#325]
When trying to build for windows 32bit the build get stuck at ` rebuilding native dependencies  dependencies=sqlite3@5.1.4 platform=win32 arch=ia32` I've waited for hours and there are no changes

![image](https://user-images.githubusercontent.com/37934074/218262130-69a3187c-43b8-439e-a888-566d7c2101fb.png)

**Comment by rotu** [comment]
Root cause https://github.com/npm/cli/issues/6662 is now fixed in [npm@10.1.0](https://github.com/npm/cli/releases/tag/v10.1.0)!

**Comment by SarkarKurdish** [comment]
> Root cause [npm/cli#6662](https://github.com/npm/cli/issues/6662) is now fixed in [npm@10.1.0](https://github.com/npm/cli/releases/tag/v10.1.0)!

Imagine if I've waited untill now to fix that, Thanks for the clarification.
