### ISSUE TITLE
can not create new project

### ISSUE THREAD

**Issue by marksaado** [saltyshiomix/nextron#326]
hello, 

I'm trying to create new app using: npx-create-nextron-app appName 
when I open the project folder and write: npm install I get a lot of errors and can't run the project. this is the first time i get this problem. any suggestions?

thanks in advance

![Capture](https://user-images.githubusercontent.com/59101445/218452759-d26c7ce8-67ec-410f-b46f-9ee0da2f2b30.PNG)

**Comment by saltyshiomix** [comment]
Hi @marksaado , could you tell me `platform` and `arch` because I can't reproduce this error.

Maybe `electron-builder install-app-deps --platform win32 --arch ia32` will fix it.

**Comment by marksaado** [comment]
Hi @saltyshiomix thanks for your replay.
I'm using windows 10. to be honest I'm new to Nextron. normally I work with Nextjs. 
how i got this error: 1- open cmd
2- write: npx create-nextron-app appName
3- cd appName
4- npm install
then I get this error
![Capture](https://user-images.githubusercontent.com/59101445/218574507-08d39f3b-9779-4689-9740-75c147b83236.PNG)

**Comment by alexis-piquet** [comment]
Could you give us your `node` and `npm` version?

``` shell
node --version
````

``` shell
npm --version
````

**Comment by marksaado** [comment]
node --version: v18.14.0
npm --version: 9.3.1

**Comment by alexis-piquet** [comment]
If you still can't start a project just created, tried to install [nvm for windows](https://github.com/coreybutler/nvm-windows/releases), it install autmatically required version of npm according to node version.

Once it install you can have many node version installed on you local and you can switch to a specific node version depending of the project you are working on.

Basics:

To install a released version:
``` shell
nvm install 19
```
To list installed versions:
``` shell
nvm list
```
To use a specific version:
``` shell
nvm use 19
```

On my side for the latest nextron I use those version of node and npm:
``` shell
npm 9.4.2 | node 18.12.0
```
