### ISSUE TITLE
Use file protocol in production

### ISSUE THREAD

**Issue by hadeeb** [saltyshiomix/nextron#33]
If we use a custom [file protocol](https://github.com/electron/electron/blob/master/docs/api/protocol.md#protocolregisterfileprotocolscheme-handler-completion) to serve static files in production, we can avoid the resolve helpers and `LinkWithIpc`.

Related: #10 ,[`electron-serve`](https://github.com/sindresorhus/electron-serve)

**Comment by saltyshiomix** [comment]
@hadeeb 

I added `LinkWithIpc` to show a way of communicating with ipcMain and ipcRenderer, but these days I come to think that it's better to remove `LinkWithIpc`.
I'm looking for a better solution.

I'll try `electron-serve` later :)

(PRs are welcome!)
