### ISSUE TITLE
typescript does not load when building?

### ISSUE THREAD

**Issue by jd0gx** [saltyshiomix/nextron#331]
runinng `yarn build` after downloading the repo gives me 

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/4531670/224206642-b67c6fee-618b-4fd9-936f-55dbef12b24f.png">

**Comment by alexis-piquet** [comment]
Hey @jd0gx. 
- What are your `node` and `npm` version? 
- What's your platform and also your platform arch?
- Wich version of typescript do you use?
- Have you set specific lint rules?

**Comment by jd0gx** [comment]
Thanks Alexis, I somehow managed to resolve it myself.
