### ISSUE TITLE
Nextron ipc-communication fails to work in production.

### ISSUE THREAD

**Issue by ruriko123** [saltyshiomix/nextron#338]
```js
import electron from 'electron';

const ipcRenderer = electron.ipcRenderer || false;
```
The "ipcRenderer" is always false in production build. It works fine in development, but doesn't seem to work after building in production.

**Comment by alexis-piquet** [comment]
Hey, nice to read you @ruriko123. You must wrap it in a context as I've explain it [here](https://github.com/saltyshiomix/nextron/discussions/357). If it solve your issuer don't forget do close it, and if you have other question don't hesitate to comeback to me. Have a nice coding day !

**Comment by 0xPT** [comment]
https://github.com/saltyshiomix/nextron/tree/main/examples/ipc-communication

So this example just doesn't work in production???
