### ISSUE TITLE
support electron 24.0.0

### ISSUE THREAD

**Issue by KaptinLin** [saltyshiomix/nextron#346]
it shows empty screen when upgrade electron from ^21.4.3  to  ^24.0.0

**Comment by irg1008** [comment]
Make sure you have nodeIntegration to false, contextIsolation to true and most important, sandbox to false.

```typescript
  const browserOptions: BrowserWindowConstructorOptions = {
    ...state,
    ...options,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: false,
      contextIsolation: true,
      enableBlinkFeatures: '',
      sandbox: false,
      ...options.webPreferences,
    },
  };
```

**Comment by KaptinLin** [comment]
it's not working.

https://github.com/KaptinLin/nextron-ts-template

**Comment by bfan1256** [comment]
I get global is undefined with this approach.

**Comment by irg1008** [comment]
> I get global is undefined with this approach.

Maybe you are accessing the global object in server side rendering. The renderer process can only access the contextBridge in client side

**Comment by irg1008** [comment]
> @irg1008, i follow your code, but it's not working still.
> 
> https://github.com/KaptinLin/nextron-ts-template
> 
> <img alt="image" width="994" src="https://user-images.githubusercontent.com/999331/232999604-ce486464-94c6-4d41-8e52-b5059ec4dec4.png">

Weirdly is working for me with latest versions from both next.js and electron so will try to upload an example repo and share it here in the next hours

**Comment by irg1008** [comment]
Okay here is a working template we use for our projects (kinda):

It uses turbo and pnpm and it has some boilerplate but I think will do the trick

https://github.com/irg1008/nextron-template

Versions:
* Electron: 24.1.2
* Next.js: 13.2.4
* Nextron: 8.5.0

Instructions:
1. Clone and install from workspace root: `pnpm i`
2. Start the app
(VSCode): Start the app from _run and debug_
(Terminal): `turbo dev --filter=app...` or just `turbo dev`

Hope it helps. You can also just look at the background/preload files to figure it out!

**Comment by irg1008** [comment]
@KaptinLin Are you getting those errors in the template or your project?

**Comment by irg1008** [comment]
Because the template provided has no errors in console for me:
![image](https://user-images.githubusercontent.com/47559427/234562725-0e752b8c-0833-4959-9297-ad32bffd8f51.png)

**Comment by KaptinLin** [comment]
You can see https://github.com/KaptinLin/nextron-template

Maybe we can't use electron-store on renderer side?

**Comment by polybean** [comment]
I think it is a nextron issue. Any chance to update the "official" templates?

**Comment by andirsun** [comment]
We are going to update the templates to Electron 24 but I can tell you that version is supported.

**Comment by yanchummar** [comment]
> Yeah that's right. The only main process object available to the renderer is the one exported in the contextBridge. electron-store is a node library and so with nodeIntegration set to false we can't use node libraries in the renderer

I'm running into a similar use case where I need nodeIntegration to be set to true, but when it is set to true, electron fails to load the nextjs app properly, any solutions for this?

**Comment by uzunhair** [comment]
[https://github.com/saltyshiomix/nextron/issues/384#issuecomment-1690094254](https://github.com/saltyshiomix/nextron/issues/384#issuecomment-1690094254)
Я дополнил ответ, это должно решить вашу проблему

**Comment by saltyshiomix** [comment]
@Taarek CC: @ShahriarKh @vandetho @tomaszczura @KaptinLin @geraldoramos @irg1008 

Sorry for late reply 🙇 

Just remove `config.target = 'electron-renderer'` in `next.config.js`. It works like a charm 🚀 

**Before**

```js
module.exports = {
  trailingSlash: true,
  images: {
    unoptimized: true,
  },
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.target = 'electron-renderer'
    }

    return config
  },
}
```

**After**

```js
/** @type {import('next').NextConfig} */
module.exports = {
  trailingSlash: true,
  images: {
    unoptimized: true,
  },
  webpack: (config) => {
    return config
  },
}
```

**Comment by MaxLiebsch** [comment]
@saltyshiomix
[fix: Support for electron v22+](https://github.com/saltyshiomix/nextron/commit/a19177b0374b1c3111e94104791c60c380e2db9d) https://github.com/saltyshiomix/nextron/issues/299 https://github.com/saltyshiomix/nextron/issues/346 https://github.com/saltyshiomix/nextron/issues/384

that aren't fixes. That is basically turning of nodeIntegration: false and remove webpack config from next.config.js which is not a fix.

**Comment by squirelo** [comment]
@MaxLiebsch Did you find a way to make it works? Thx

**Comment by squirelo** [comment]
@saltyshiomix Hi, I've been stuck since many months on this one. Is there a way to turn nodeintegration:true while using electron v22+ ? Thx for your help

**Comment by openarun** [comment]
The issue still persists from electron v22 to v29 too. Either need a fix with using nodeintegration:true or an alternative method to it.
@saltyshiomix

**Comment by squirelo** [comment]
@saltyshiomix It has been a year you removed all possibility to use nextron with nodeintegration true
