### ISSUE TITLE
Using localStorage ?

### ISSUE THREAD

**Issue by code-creativeapps** [saltyshiomix/nextron#347]
Hello, 

Thanks for the great package by the way, I'm so happy to code the electron app with Next!

It seems like I'm not able to persist data in localStorage, hot reloading the app after saving a file wipes the data. 
Is this a normal behavior or am I doing something wrong ?

**Comment by fyfirman** [comment]
I just built the app with local storage. I used Zustand with `persist` plugin. There would be an error from Next about Hydration that could be fixed. What error occurs to you?
