### ISSUE TITLE
High severity on webpack version

### ISSUE THREAD

**Issue by bricevrs** [saltyshiomix/nextron#350]
Hello! 👋

Regarding the vulnerability in Webpack versions 5.0.0 to 5.75.0, the official Webpack team has already released a security patch for this issue in version 5.75.1. The vulnerability was related to a potential malicious code execution through the "file-loader" and "url-loader" plugins.

Therefore, I recommend updating the "webpack" package to version 5.80.0, which is currently the last version

```diff
-    "webpack": "5.75.0"
+    "webpack": "5.80.0"
```

**I posted a pull request**

https://github.com/saltyshiomix/nextron/pull/351

**Comment by alexis-piquet** [comment]
You have forgot to mention your PR 💋.
https://github.com/saltyshiomix/nextron/pull/351

Let me have a look on it and test it before approve it.

**Comment by bricevrs** [comment]
Alright thank you 😉

**Comment by andirsun** [comment]
Fixed here https://github.com/saltyshiomix/nextron/pull/351
