### ISSUE TITLE
Require is not defined, when using nextauth

### ISSUE THREAD

**Issue by Mogeiman** [saltyshiomix/nextron#364]
I am building a nextron app with typescript. While trying to integrate NextAuth into to handle authentication, I got the above error. This only happens when I wrap SessionProvider around my app. I am importing everything the write way, and nowhere in my client code am I using `require`.

` 
<SessionProvider session={session}>
      <LayoutComponent>
          <Component {...pageProps} />
      </LayoutComponent>
    </SessionProvider>
`
    
I get the same error when I try to use axios. Even without calling the axios request, as long as I import and use it somewhere in my code the error appears. I am willing to provide more code and answer more quesitons, so please feel free to ask. I truly need the help as this is a next app for a business I was trying to convert a desktop app.

**Comment by alexis-piquet** [comment]
Hey @Mogeiman , nice to read you! You can't use `NextAuth` with `Nextron`.
But you can implement an authenticate window before displaying your application window and display your application window once your user is authenticated, store your credential using `electron-store` and allow your application to get it using a custom context in your _app.ts file.

You can find a basic usage of `electron-store` [here](https://github.com/saltyshiomix/nextron/discussions/357)

In waiting of reading you again, I wish you a nice coding day :).

**Comment by Mogeiman** [comment]
Thanks Alexis, I will do just that.
