### ISSUE TITLE
Packaging - please wait a momentnpm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by andyTsing** [saltyshiomix/nextron#37]
I have a problem，When I build, the error message is as follows：
D:\Temp\TXSSPrinting>npm run build

> my-nextron-app@1.0.0 build D:\Temp\TXSSPrinting
> node nextron/nextron.js build

√ Clearing previous builds
√ Building renderer process
√ Building main process
| Packaging - please wait a momentnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-nextron-app@1.0.0 build: `node nextron/nextron.js build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-nextron-app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

The following is the error log：
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andyTsing\AppData\Roaming\npm-cache\_logs\2019-06-11T15_06_10_997Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.3.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle my-nextron-app@1.0.0~prebuild: my-nextron-app@1.0.0
6 info lifecycle my-nextron-app@1.0.0~build: my-nextron-app@1.0.0
7 verbose lifecycle my-nextron-app@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle my-nextron-app@1.0.0~build: PATH: D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Temp\TXSSPrinting\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files\AdoptOpenJDK\jdk-12.0.1.12-hotspot\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files\AdoptOpenJDK\jdk-12.0.1.12-hotspot\\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft VS Code Insiders\bin;C:\Program Files\Git\cmd;D:\Program Files\Calibre2\;D:\Program Files\Microsoft Visual Studio\Shared\Python36_64;D:\Depot;C:\Python27;D:\Program Files\Redis\;C:\ProgramData\chocolatey\bin;D:\Program Files\nodejs\;D:\Flutter\bin;D:\Flutter\bin\cache\dart-sdk\bin;C:\Users\andyTsing\AppData\Roaming\Pub\Cache\bin;D:\Go\bin;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\andyTsing\AppData\Roaming\npm;C:\Users\andyTsing\go\bin
9 verbose lifecycle my-nextron-app@1.0.0~build: CWD: D:\Temp\TXSSPrinting
10 silly lifecycle my-nextron-app@1.0.0~build: Args: [ '/d /s /c', 'node nextron/nextron.js build' ]
11 silly lifecycle my-nextron-app@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle my-nextron-app@1.0.0~build: Failed to exec build script
13 verbose stack Error: my-nextron-app@1.0.0 build: `node nextron/nextron.js build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:200:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:200:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid my-nextron-app@1.0.0
15 verbose cwd D:\Temp\TXSSPrinting
16 verbose Windows_NT 10.0.17763
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.3.1
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error my-nextron-app@1.0.0 build: `node nextron/nextron.js build`
22 error Exit status 1
23 error Failed at the my-nextron-app@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by saltyshiomix** [comment]
@andyTsing 

What example do you use?

**Comment by andyTsing** [comment]
Hello：

   I use this command: nextron init my-app --template with-javascript-material-ui create the application, init and npm run dev is successed, Problems encountered while running npm run build.



    TKS.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Yoshihide Shiono <notifications@github.com>
发送时间: Wednesday, June 12, 2019 8:19:43 AM
收件人: saltyshiomix/nextron
抄送: andyTsing; Mention
主题: Re: [saltyshiomix/nextron] Packaging - please wait a momentnpm ERR! code ELIFECYCLE (#37)


@andyTsing<https://github.com/andyTsing>

What example do you use?

―

**Comment by hadeeb** [comment]
It looks like an issue with packaging.
Can you run `npx electron-builder` in the project directory and attach the logs?

**Comment by andyTsing** [comment]
ok,let me try it☕

**Comment by andyTsing** [comment]
Due to network reasons, Electron build cannot download resources such as winCodeSign, nsis, nsis-resources, etc., causing the above problems.
        However, before the npx electron-builder is executed, the log does not have a clear prompt; when using npx electron-builder, the cause of the problem can be clarified, and the missing dependencies are installed according to the prompts, and the execution is successful; further, npm run build is executed. Successful.
Thank you.
The idea you provided is the key to discovering the problem, ^_^

**Comment by saltyshiomix** [comment]
@andyTsing 

Could you try to run `npx electron-builder install-app-deps` inside your project?

This command ensures your native dependencies are always matched electron version :)

**Comment by andyTsing** [comment]
tks all boys^_^
