### ISSUE TITLE
The image cannot be loaded!~

### ISSUE THREAD

**Issue by Yukixieyuya821** [saltyshiomix/nextron#370]
Using the Image component to load images fails to load them properly.

Local image:
![image](https://github.com/saltyshiomix/nextron/assets/53206696/2d3bdd23-a626-4a91-bafa-5a9d7a2a3ee2)

External link image：
![image](https://github.com/saltyshiomix/nextron/assets/53206696/6fd801d4-cb7b-4572-a16d-070b194fab21)

**Comment by alexis-piquet** [comment]
Hey, nice to read you @Yukixieyuya821, You can find a solution of your issue [here](https://github.com/saltyshiomix/nextron/discussions/371). If it's solve your issue plz close it. 😘

**Comment by Yukixieyuya821** [comment]
Thank you for your response, but it doesn't address my issue. It's because I'm using the built-in Image component from 'next/image', not the native 'img' tag.
