### ISSUE TITLE
Thank you for your response, but it doesn't address my issue. It's because I'm using the built-in Image component from 'next/image', not the native 'img' tag.

### ISSUE THREAD

**Issue by Yukixieyuya821** [saltyshiomix/nextron#372]
Thank you for your response, but it doesn't address my issue. It's because I'm using the built-in Image component from 'next/image', not the native 'img' tag.

_Originally posted by @Yukixieyuya821 in https://github.com/saltyshiomix/nextron/issues/370#issuecomment-1565144545_

**Comment by Yukixieyuya821** [comment]
I found a solution. The reason is that "next export" does not support "_next/image" after exporting, and it requires the Next.js server for successful parsing. To solve this in the app, you need to change the URL of the "img" to your own Next.js server address.

**Comment by alexis-piquet** [comment]
Exactly, don't hesitate de next time where you encounter an issue to explain with the full context to it be resolved fast. Could you share how you do it [in the discussion section.](https://github.com/saltyshiomix/nextron/discussions/categories/show-and-tell)

**Comment by Yukixieyuya821** [comment]
Of course, it's possible.
