### ISSUE TITLE
Build failed with errors with yarn

### ISSUE THREAD

**Issue by Naitik4516** [saltyshiomix/nextron#374]
# This file contains the result of Yarn building a package (my-nextron-app@workspace:.)
# Script name: postinstall

  • electron-builder  version=23.6.0
  • loaded configuration  file=E:\Programming\Electron apps\gravia-5\electron-builder.yml
  ⨯ Cannot compute electron version from installed node modules - none of the possible electron modules are installed and version ("^21.3.3") is not fixed in project.
See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246

**_I am getting this error when I run yarn install or yarn _**

**Comment by alexis-piquet** [comment]
Hey, nice to read you @Naitik4516 , could you give us your lock package file ? Have you install nextron/electron -g on your machine?

**Comment by saltyshiomix** [comment]
@Naitik4516 

Any updates?

I just closed this issue but feel free to reopen it if you have any troubles :)
