### ISSUE TITLE
Nextron tray menue

### ISSUE THREAD

**Issue by noevermaurice** [saltyshiomix/nextron#395]
I would like to use the electron tray menu in nextron for macOS how do i implement this and where ? please code example

**Comment by makeusabrew** [comment]
Disclaimer: I'm only just getting started with Nextron, but...

As far as I can tell, creating a tray menu is exactly the same as in a normal Electron app. So, the best code example to start off with would be the official [Electron Tray docs](https://www.electronjs.org/docs/latest/tutorial/tray).

You can configure your tray once `app.whenReady()` has fired, e.g. you could create and configure it around here: https://github.com/saltyshiomix/nextron/blob/main/examples/_template/ts/main/background.ts#L15

(Note that in the official Electron examples the `tray` object is declared outside of the promise callback, which you should respect - I believe it's to stop the object being accidentally garbage collected).

**Comment by saltyshiomix** [comment]
@makeusabrew 
Thank you for your comment!

@noevermaurice 
Any updates on this?
