### ISSUE TITLE
app.quit() using JavaScript.

### ISSUE THREAD

**Issue by pixkk** [saltyshiomix/nextron#396]
For example, i want use next code (client side render):
```js
const {ipcRenderer} = require('electron');
const closeApp = document.getElementById('closeApp');
closeApp.addEventListener('click', () => {
    ipcRenderer.send('close-me')
});
```

Any mention of "require('electron')" in the page code generates the error "./node_modules/electron/index.js:1:0 Module not found: Can't resolve 'fs'"  (module FS installed and used in another file successfully)

Is it possible quit app by JavaScript?

PS.: it can bypassed by window.close(), but is it best method of closing app?

**Comment by makeusabrew** [comment]
Look into exposing a minimal subset of the electron API to your renderer process via a context bridge and invoking an IPC send from methods you expose via that bridge. This section of the official Electron docs covers the pattern you're after: https://www.electronjs.org/docs/latest/tutorial/ipc#pattern-2-renderer-to-main-two-way

**Comment by pixkk** [comment]
> Look into exposing a minimal subset of the electron API to your renderer process via a context bridge and invoking an IPC send from methods you expose via that bridge. This section of the official Electron docs covers the pattern you're after: https://www.electronjs.org/docs/latest/tutorial/ipc#pattern-2-renderer-to-main-two-way

Thanks for the answer. It seems like I solved the problem a long time ago, so I’ll write an answer for those who came here.

Play with the renderer settings (examples/........./renderer/next.config.js, config.target option). If you have a problem using IPC, look at the settings from the project template where IPC is used.

**Comment by Mrx-dev** [comment]
what should I change in (renderer/next.config.js) ?
