### ISSUE TITLE
App fails to build if I use ipcRenderer

### ISSUE THREAD

**Issue by 0xPT** [saltyshiomix/nextron#401]
As seen in the README and in the ipc-communication example, when I include this code in the file it doesn't work and gives me this error.

```
const ipcRenderer = electron?.ipcRenderer || false;
      
useEffect(() => {
    if (ipcRenderer) {
      ipcRenderer.on("channel", (event, data) => {
        setData(data);
      });
      return () => {
        ipcRenderer.removeAllListeners("channel");
      };
    }
 }, []);
  ```
  
  
`Error occurred prerendering page "/login". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again`

**Comment by AbdeenM** [comment]
@0xPT have you managed to find a solution?

**Comment by 0xPT** [comment]
@AbdeenM 

I did figure out a solution for this.

  useEffect(() => {
    const ipcRenderer = require("electron").ipcRenderer || false;

    if (ipcRenderer) {
      ipcRenderer.on("authorize", (event, data) => {
        setSession(data);
      });
      return () => {
        ipcRenderer.removeAllListeners("authorize");
      };
    }
  }, []);

**Comment by AbdeenM** [comment]
Still running into the same problem, did you come across this?
```
../../../node_modules/electron/index.js:1:0
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./pages/index.tsx
```

**Comment by 0xPT** [comment]
> Still running into the same problem, did you come across this?
> 
> ```
> 
> ../../../node_modules/electron/index.js:1:0
> 
> Module not found: Can't resolve 'fs'
> 
> 
> 
> https://nextjs.org/docs/messages/module-not-found
> 
> 
> 
> Import trace for requested module:
> 
> ./pages/index.tsx
> 
> ```

Could you provide the code where this is occurring?

**Comment by adammenges** [comment]
I'm running into the same thing @0xPT & @AbdeenM 

home.tsx
``` jsx
import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import ipcRenderer from "electron";
import { useEffect } from 'react';


function sendMessage() {
  console.log("sending message");
  useEffect(() => {
    const ipcRenderer = require("electron").ipcRenderer || false;
  
    if (ipcRenderer) {
      ipcRenderer.send("message", "Hello");
    }
  }, []);
}

export default function HomePage() {
  return (
    <React.Fragment>
      <Head>
        <title>Adam's Dumb App</title>
      </Head>
      <div className="grid grid-col-1 text-2xl w-full text-center">
        <div onClick={sendMessage}> click meeeee </div>
      </div>
      <div className="mt-1 w-full flex-wrap flex justify-center">
        <Link href="/next">Go to next page</Link>
      </div>
    </React.Fragment>
  );
}
```

![CleanShot 2024-05-08 at 15 32 58@2x](https://github.com/saltyshiomix/nextron/assets/817438/d39e8635-b7ae-408a-b383-c395815eef7f)
I'm not importing `fs`. Just ran into this and still debugging.

**Comment by adammenges** [comment]
got it: https://github.com/saltyshiomix/nextron/issues/415
