### ISSUE TITLE
How i can use Nextron + tailwindcss +Javascript  without using typescript

### ISSUE THREAD

**Issue by Ahtisham-01** [saltyshiomix/nextron#408]

**Comment by bm777** [comment]
@Ahtisham-01  

You need to do that separately like in Nextjs 12.x.

- Create Nextron app with `npx create-nextron-app`.
- Install manually Tailwindcss in your project following [tailwindcss procedure](https://tailwindcss.com/docs/installation)
- add use it and ensure you have a tailwindcss file inside the `renderer` folder as follows.

<img width="253" alt="Screenshot 2023-10-04 at 14 12 54" src="https://github.com/saltyshiomix/nextron/assets/29865600/379b0c57-8bc1-48aa-aa65-5ee6496148e1">

**Comment by bm777** [comment]
@Ahtisham-01 
Another way is to install the example Tailwindcss + TypeScript and remove the TS config:
- by removing tsconfig.js
- by renaming the ts or tsx file into js or jsx resp. (eventually, change the content to look js code.)

or 

This is the [template](https://github.com/bm777/nextron-speed-launch.git) I'm using in another issue #410. it is JS + Tailwindcss. you can clone it.
