### ISSUE TITLE
Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by hamasbutt786** [saltyshiomix/nextron#409]
![image](https://github.com/saltyshiomix/nextron/assets/111352577/45baec33-e107-494a-8954-b4b5cc43802e)

@saltyshiomix 

When i use import electron in my next js environment in the render it shows this kind of error. How am i able to fix it.

**Comment by bm777** [comment]
@hamasbutt786 


In a Next.js project (or even in Nextron by inheritance), the fs (File System) module cannot be imported and used directly. The fs module is a core Node.js module for interacting with the file system. There are several reasons why you cannot use it directly in Next.js for client-side code.

But you can use [IPC](https://github.com/saltyshiomix/nextron/tree/main/examples/ipc-communication), and get `fs` used in node.js backend.

**Comment by hamasbutt786** [comment]
@bm777

isn't the ipc is getting imported from electron?

**Comment by hamasbutt786** [comment]
@bm777

my code is showing like this can you help here?

![code](https://github.com/saltyshiomix/nextron/assets/111352577/d2ec307f-57d6-4a42-a96a-5fbb32b1be1c)

**Comment by bm777** [comment]
@hamasbutt786 please can you paste the code instead of the picture?
Thanks
