### ISSUE TITLE
Can I make this work in a monorepo?

### ISSUE THREAD

**Issue by nandorojo** [saltyshiomix/nextron#412]
I have a monorepo with my Next.js app in `apps/next`. I am hoping to create a new app at `apps/nextron`. Can I use import my Next.js app from `apps/next` and use that in `apps/nextron` to render the electron app? 

Which is to say: can I render my existing Next.js app from a separate monorepo package in my electron app?

**Comment by bm777** [comment]
@nandorojo 
Yes, of course, you can do that.
To avoid issues while you are importing, you can create an empty separate Nextron app.
Then move the logic from your Next.js `pages/` folder into the `renderer/` folder.

It worked for me, try it and let me know.

**Comment by bennettfrazier** [comment]
@nandorojo are you planning to share your results if you're working on a starter? (: If you're embedding with dripsy, solito, and/or moti, would love to see what you come up with!

**Comment by nandorojo** [comment]
I managed to get it spun up with Tauri instead. But I found that plainly rendering my Next app as-is in a desktop container had no benefits over a browser. In fact it was worse without a back button / URL so I dropped it. I mainly wanted this for notifications, so I added those using the Web Notifications API.

**Comment by nandorojo** [comment]
But thank you @bm777 for the reply and great work here. My use case just didn't pan out for using desktop.
