### ISSUE TITLE
Nextron database Produccion Build 

### ISSUE THREAD

**Issue by divol89** [saltyshiomix/nextron#416]
Hello , im struggling to find the way how to use my database ,locally with nextron on production is it restricted ? i build 1 simple  POST method + sqlite3 database and after npm run build is not working ,

here is the build warning : 

warn  - Statically exporting a Next.js application via `next export` disables API routes.
This command is meant for static-only hosts, and is not necessary to make your application static.
Pages in your application without server-side data dependencies will be automatically statically exported by `next build`, including pages powered by `getStaticProps`.
Learn more: https://nextjs.org/d

**Comment by divol89** [comment]
thanks , i practiced a lot now i understand i did. a lot of research :D

**Comment by bm777** [comment]
Great. and sorry for the late reply @divol89
