### ISSUE TITLE
SSR for web components?

### ISSUE THREAD

**Issue by vendramini** [saltyshiomix/nextron#42]
Good night!

First of all, excellent work! I will definitively adopt this lib to build my desktop app.

Is possible to render Web Components on SSR using your solution? To be more specific, I would like to use http://onsen.io

Regards.

**Comment by saltyshiomix** [comment]
@vendramini 

At first, thank you for your graceful comments!

Next.js is the SSR framework, so it is difficult to handle them in one place because `onsenui` can't do SSR.

I recommend to use SPA instead :)
