### ISSUE TITLE
Unable to run python when building a Windows App.!?

### ISSUE THREAD

**Issue by bryantz13** [saltyshiomix/nextron#421]
I have a question I'd like to ask. I created a python file in renderer -> pages -> script-python -> python.py and I used IPC to run the python file using the spawn of child_process to run the python file through IPC. I found The problem is that When I start the system through localhost, the system can work normally, but when I build a Windows App, the system cannot run the python file. What is the cause? And can you help me? Or is there any example? please help me

**Comment by bm777** [comment]
@bryantz13 I've answered to this question here -> #21

**Comment by bm777** [comment]
https://github.com/saltyshiomix/nextron/issues/427#issuecomment-1843946241

Here is the Python example.
