### ISSUE TITLE
Child process not working in packaged app

### ISSUE THREAD

**Issue by kentezrabetita** [saltyshiomix/nextron#427]
Hello,

I am experiencing an issue related to the execution of a child process in the packaged version of my Nextron application. The child process works as expected in the development environment, but fails to execute when the application is packaged. I am currently testing on an M1 Mac.

The file structure in the main directory is as follows:
```
main/
├─ helpers/
├─ background.ts
├─ ipc.ts
├─ worker.ts
```

In my `ipc.ts` file, I fork a child process from `worker.ts`:

```javascript
const child = fork('./main/worker.ts'); // i think the problem also lies here

child.on('message', (message) => {
  console.log('Received message from child:', message);
});

child.on('exit', (code) => {
  console.log(`Child process exited with code ${code}`);
});

export const setupIpcHandlers = () => { // this function is called in the `background.ts`
  ipcMain.on('store-image', async (event, image) => {
    const user: any = state.store.get('user_data');
    const { id } = user;

    if (child.connected) {
      child.send({ image: image, user_id: id });
    }
  });
}
```

In the `worker.ts` file, I handle the 'message' event from the main process:

```javascript
process.on('message', async (message) => {
  // handles a basic HTTP request to upload image
});
```

In development, the main process successfully sends the message and the child process performs as expected. However, in the packaged app, the child process doesn't seem to be executing.

Despite adding 'exit' and 'error' event handlers to the child process, no error messages or exit codes have been generated.

Upon examining the built version of the app in the `./app` directory, I noticed the absence of a `worker.js` file or other files that i've added. However, references to the worker code exist in `background.js`. This leads me to suspect that the issue might be related to the way I'm referencing the worker file in `const child = fork('./main/worker.ts')`;.

Any guidance on this issue would be greatly appreciated, particularly on getting the child process to work correctly in the packaged app.

Thank you!

**Comment by kentezrabetita** [comment]
Hey @bm777, that's awesome news! I appreciate your work on this and thanks for the good heads up. Looking forward to your PR!

**Comment by bm777** [comment]
@JesTery58 can you be more precise please?

**Comment by JesTery58** [comment]
do child.send() function want a channel ?

**Comment by bm777** [comment]
@JesTery58 basically when using IPC, I always pass the channel as str, in this case, the channel was : [here](https://github.com/saltyshiomix/nextron/blob/a4211e0b10130bba9b013a548489fd8437efb82e/examples/basic-js-python/renderer/pages/home.jsx#L17C20-L17C23)
