### ISSUE TITLE
API Route support

### ISSUE THREAD

**Issue by filippozanfini** [saltyshiomix/nextron#445]
Is there any possibility of having Routes API support with Nextron? Or is there some other method?

**Comment by bm777** [comment]
@filippozanfini , sorry for the late reply.
After the build, there is no dynamic routing. The workaround, we all have is to build the app in a single file, then build components on top of it.

**Comment by Psycokwet** [comment]
Seems to be a duplicate of [work with api route? #43](https://github.com/saltyshiomix/nextron/issues/43)
I'll let you discuss that there if you want to dig more :) Good luck with what you want to do !
