### ISSUE TITLE
when app router version is scheduled to be released

### ISSUE THREAD

**Issue by applepykim** [saltyshiomix/nextron#449]
I always use Nextron well. Thank you every time!

app router Nextjs 13 or higher is upcomming, but I would like to know when it is scheduled to be released.

**Comment by yt-dlx** [comment]
**Same Here !**

**Comment by rixcian** [comment]
The latest release [v8.15.0](https://www.npmjs.com/package/nextron/v/8.15.0) supports Next.js v13.

You can look into the [examples](https://github.com/saltyshiomix/nextron/tree/main/examples) folder, all example projects are running on Next.js v13.

**Comment by saltyshiomix** [comment]
Thank you, @rixcian !

But we should be careful, electron can handle only static files when production build, so nextron doesn't support React Server Components.

**Comment by pixelass** [comment]
I agree, for electron/nextron it is a lot easier to stick to pages, this is especially helpful when working with multi-lingual apps as seen in [the i18next example](https://github.com/saltyshiomix/nextron/tree/main/examples/with-next-i18next)

Don't overthink it. Use what is best for the environment you're working in.

> An SUV might look and feel nice but doesn't give you benefit in a big city, quite the contrary tbh 🤣

**Comment by saltyshiomix** [comment]
We can't support Next.js app router: https://github.com/saltyshiomix/nextron/issues/475#issuecomment-2241396038

I'll close this issue, but feel free to reopen it if any updates :)
