### ISSUE TITLE
publish

### ISSUE THREAD

**Issue by bkniffler** [saltyshiomix/nextron#45]
Hi,
Whats the recommended way to publish? I know I can use `electron-builder --publish`, but this will also rebuild the application bundles. And `nextron build` will also always build application bundles, so I'm not sure how to build & publish without building twice. 

The best solution for me would be to have `nextron build` which would only create JS bundles. Or if nextron would accept the `--publish` argument. Or do I miss something?

**Comment by bkniffler** [comment]
Here is one possible solution, feel free to close the PR if you don't like that approach: https://github.com/saltyshiomix/nextron/pull/46

**Comment by bkniffler** [comment]
Oh, I noticed I can still publish through electron builder config. Nevermind :)

**Comment by saltyshiomix** [comment]
@bkniffler 

No problem :)
If you have any questions, feel free to contact me 👍

**Comment by zdenham** [comment]
How did you end up configuring it to publish with electron builder config? Just including the "publish" key didn't work for me, so currently I'm building twice:

```
  "build": "nextron build",
  "release": "yarn run build && electron-builder --publish always",
```

**Comment by bkniffler** [comment]
This should work: 
```
{
 "build": "nextron build",
 "release": "nextron build"
}
```
Electron builder should detect it is called from `release` script and take care of everything.
