### ISSUE TITLE
install directly with app router?

### ISSUE THREAD

**Issue by applepykim** [saltyshiomix/nextron#455]
After installing nextron, it is installed in the page folder.

Is there still no feature to install directly with app router?

**Comment by hammadtariq321** [comment]
Same here i need a command by that my default project will be app router

**Comment by saltyshiomix** [comment]
@applepykim @hammadtariq321 

Sorry for late reply.

We can't support Next.js app router: https://github.com/saltyshiomix/nextron/issues/475#issuecomment-2241396038
