### ISSUE TITLE
IPC example

### ISSUE THREAD

**Issue by yt-dlx** [saltyshiomix/nextron#459]
Dear Devs,

I hope this message finds you well. I'm currently working with nextron based on Next.js 13.5.6 and I'm facing some challenges incorporating IPC (Inter-Process Communication) into my project. Despite my efforts, I haven't been able to locate any IPC-based examples in your documentation or resources.

Could you please provide some guidance or examples on how to effectively implement IPC within a nextron project? Any assistance you could offer would be greatly appreciated.

Thank you for your time and support.

**Comment by bm777** [comment]
@yt-dlx Hi, in this template, you can see how we send data from the frontend, to the js backend via [IPC](https://github.com/saltyshiomix/nextron/tree/main/examples/basic-lang-javascript-python).

-----
In that example: 
- front the frontend, we send `window.ipc.send('run-sh', value)` via this [ipc.send](https://github.com/saltyshiomix/nextron/blob/651967d7df3d0f7cb306f7d4296866f994fbeb5d/examples/basic-lang-javascript-python/renderer/pages/home.jsx#L48)
- and, in the backend, we receive the signal via [ipcMain.on](https://github.com/saltyshiomix/nextron/blob/651967d7df3d0f7cb306f7d4296866f994fbeb5d/examples/basic-lang-javascript-python/main/background.js#L41C1-L45C3):

```javascript
ipcMain.on('run-sh', async (event, value) => {
  console.log('DEBUG: starting process') // for dev mode
  event.sender.send('log', 'Running...') // for prod mode
  await startProcess(event, value)
})
```

I hope it helps :)

**Comment by yt-dlx** [comment]
![Capture](https://github.com/saltyshiomix/nextron/assets/160623192/fdfff5ef-5542-427c-ae38-8a2c6ad4f1fd)


what am i doing wrong? I cloned the example folder > changed 'pages/home.tsx to index.tsx' and ran 'yarn dev'

**Comment by bm777** [comment]
@yt-dlx doo you have `preload.js` file inside the main folder?
that might be the cause, it is define and exposed in that file.

And when creating a windows, you should pass it like this:
```javascript
mainWindow = createWindow('main', {
            width: 1000,
            height: 700,
            webPreferences: {
              preload: path.join(__dirname, 'preload.js'),
            }
          })
```

**Comment by yt-dlx** [comment]
@bm777 in this version there was no preload.js 'https://github.com/saltyshiomix/nextron/tree/main/examples/basic-lang-javascript-python' 

can i use the preload.js from the repo?

**Comment by bm777** [comment]
It should appear if you do:
```bash
npx create-nextron-app my-app --example basic-lang-javascript-python
```
If not, you can copy this [preload.js](https://github.com/saltyshiomix/nextron/blob/main/examples/_template/js/main/preload.js) and past it in your `main/`

**Comment by yt-dlx** [comment]
I have tried with the preload.js but I am facing the same error. 
Kindly please help me: **https://github.com/yt-dlx/yt-dlx/tree/main/package**


![image](https://github.com/saltyshiomix/nextron/assets/160623192/c909e374-1599-4b69-a164-a2801bcd4158)

**Comment by Psycokwet** [comment]
Instead of cloning to start your working directory, did you create a whole new project from ```npx create-nextron-app my-app --example basic-lang-javascript-python``` ? This will help greatly if you don't start from a clone.

**Comment by yt-dlx** [comment]
@Psycokwet I tried with the yarn create but same error of window.ipc.
I have also tried the preload.js.

**Comment by bm777** [comment]
@yt-dlx  Oh I got the issue:
There is a `helper` folder missing. @Psycokwet is right, you didn't create the project with that template. if you did it, it would have automatically also created that folder. it seems, you are trying to integrate it into your project.

The missing folder is this ->
[https://github.com/saltyshiomix/nextron/tree/651967d7df3d0f7cb306f7d4296866f994fbeb5d/examples/_template/js/main](https://github.com/saltyshiomix/nextron/tree/651967d7df3d0f7cb306f7d4296866f994fbeb5d/examples/_template/js/main)

**Comment by yt-dlx** [comment]
**@bm777 @Psycokwet**

I've implemented the changes using 'yarn create' as suggested, but the issue persists. Would you mind reviewing the details?

You can find the commit with the updates here: [https://github.com/yt-dlx/yt-dlx/tree/main/package](https://github.com/yt-dlx/yt-dlx/tree/main/package)

**Comment by Psycokwet** [comment]
If you really did start your project with ```npx create-nextron-app my-app --example basic-lang-javascript-python```
You should have this file structure 
![Screenshot 2024-05-23 at 10 17 55](https://github.com/saltyshiomix/nextron/assets/14911120/a388afa3-8463-48cf-9311-6b10ff7bb61e)

But in your github example, I see that : 
![Screenshot 2024-05-23 at 10 18 15](https://github.com/saltyshiomix/nextron/assets/14911120/69b4748d-48d2-40d8-8fcc-8b231543e23d)

Those are widely differents, what did you do ?

**Comment by Psycokwet** [comment]
Note that a fresh project from 
```npx create-nextron-app my-app --example basic-lang-javascript-python
cd my-app
npm install && npm run dev```

This exact set of command launch the app on my mac

**Comment by yt-dlx** [comment]
@Psycokwet 

### I followed these steps:
- npx create-nextron-app my-app --example basic-lang-javascript-python
- cd my-app
- npm install && npm run dev


_Yet the same issues. **window.ipc**_

### Tested Environments:
- ubuntu preview WSL 2
- garuda linux


### Commit:
- https://github.com/yt-dlx/yt-dlx/tree/5e3f94ecc6a5a3b3d45dadda4d2043d9f0005841/package

**Comment by yt-dlx** [comment]
Devs, any help please

**Comment by yt-dlx** [comment]
Thnks guys. I have fixed the issue using electron-vite
