### ISSUE TITLE
error: unknown option '-o'

### ISSUE THREAD

**Issue by msamgan** [saltyshiomix/nextron#467]
error: unknown option '-o'

Cannot build electron packages:
Error: Command failed with exit code 1: next export -o /Users/msamgan/Projects/digilink/mns_offline/app /Users/msamgan/Projects/digilink/mns_offline/renderer

I am facing this. Can anyone help me in this.

it was working like a few days ago.

**Comment by msamgan** [comment]
moreover  ⨯ 
    `next export` has been removed in favor of 'output: export' in next.config.js.
Learn more: https://nextjs.org/docs/app/building-your-application/deploying/static-exports

please can we make an update in the package regarding this.

**Comment by msamgan** [comment]
the issue is in next 14. it works with next 13.

**Comment by arabovs** [comment]
Here's the actual nextjs error:
`"next export" does not work with App Router. Please use "output: export" in next.config.js https://nextjs.org/docs/advanced-features/static-html-export
error Command failed with exit code 1.`

**Comment by saltyshiomix** [comment]
@arabovs 

Sorry for inconvenience. Could you try nextron v9 or v8.24.0?

**Comment by arabovs** [comment]
Thanks @saltyshiomix , will test today

**Comment by msamgan** [comment]
ok. is there any special migration guide, anything special to take care while updating ?

**Comment by saltyshiomix** [comment]
@msamgan 

Sorry for inconvenience!

Please follow this(update next.config.js):
https://github.com/saltyshiomix/nextron/issues/442#issuecomment-2171149218

**Comment by msamgan** [comment]
thanks, i will make the appropriate updates and will get back to you.

**Comment by saltyshiomix** [comment]
@msamgan 

Thank you very much, too!

Feel free to mention me.

**Comment by saltyshiomix** [comment]
@msamgan 
Any updates? If you have troubles, feel free to ask me :)

**Comment by saltyshiomix** [comment]
If you have any troubles, feel free to open the issue :)

**Comment by alieldeba** [comment]
@saltyshiomix 
I am working with next.js app router and when I write "output": "export" in next.config.js the middleware.ts file does not work and when I remove the "output": "export" the build does not work.

what should I do ?

**Comment by alieldeba** [comment]
To all who is struggling with nextron just read this article it will fix all your problems.
https://www.saybackend.com/blog/03-electron-nextjs-ssr

You will go back to nextjs 14 after this blog @msamgan

**Comment by msamgan** [comment]
thanks @alieldeba. I will have a look.
