### ISSUE TITLE
Support for pnpm

### ISSUE THREAD

**Issue by saltyshiomix** [saltyshiomix/nextron#48]
Related #47

**Comment by bkniffler** [comment]
And https://github.com/saltyshiomix/nextron/pull/49 :)

**Comment by saltyshiomix** [comment]
@bkniffler 

Electron can't resove pnpm's node_modules structures, especially when production build :(

Any ideas?

**Comment by bkniffler** [comment]
Not sure, maybe we'll need to create a simple nextron/pnpm example repository. Did you try it on a simple app that you can upload?

**Comment by saltyshiomix** [comment]
@bkniffler

Ok, I'll make a simple example repo :+1:

**Comment by saltyshiomix** [comment]
@bkniffler 

Sorry for late creating the example repo 🙏 

I'll create one or tackle the issue this week 👍

**Comment by saltyshiomix** [comment]
@bkniffler 

Sorry for late replying your comments.

I make the example repo here:

https://github.com/saltyshiomix/nextron-for-pnpm

**Comment by saltyshiomix** [comment]
@bkniffler 

Since `pnpm@^4`, `--shamefully-hoist` is supported and this worked well 👍

**Comment by saltyshiomix** [comment]
If you have any troubles, feel free to issue me up :)
