### ISSUE TITLE
Include a .gitignore

### ISSUE THREAD

**Issue by lacymorrow** [saltyshiomix/nextron#56]
It may be a personal choice, but I think a `.gitignore` file with:
```
app
dist
node_modules
```
would be nice to include in the scaffold

**Comment by saltyshiomix** [comment]
@lacymorrow 

You use create-nextron-app?

Nextron has already gitignore template here:

https://github.com/saltyshiomix/nextron/blob/master/examples/_template/gitignore.txt

Anyway, I'll add .gitignore to the initial template for all use cases :+1:

**Comment by saltyshiomix** [comment]
@lacymorrow 

Just published `create-nextron-app@3.0.0` which fixes this issue :)

**Comment by lacymorrow** [comment]
@saltyshiomix Great! Yes I think having a gitignore in the `create-nextron-app` is helpful for new users.

**Comment by saltyshiomix** [comment]
@lacymorrow 

Thank you for your reporting the issue :)
