### ISSUE TITLE
Can I run next server in production build?

### ISSUE THREAD

**Issue by watanabeyu** [saltyshiomix/nextron#57]
Hi.

I want to run node process in production build app.
In the development environment, run server, so execute node in pages/api/hoge.ts, but production build app can't run.
The reason is that I want to run ffmpeg and image processing

please teach me.

**Comment by saltyshiomix** [comment]
@watanabeyu 

We can't run the next server or any other servers except electron main process, because it is a security vulnerability.

So we can't use API routes in production.
API servers should be outside electron.

Cheers,

**Comment by watanabeyu** [comment]
Hi @saltyshiomix 
OK, thanks to reply!
