### ISSUE TITLE
support for multiple processes

### ISSUE THREAD

**Issue by falafeljan** [saltyshiomix/nextron#60]
hi! we love nextron, it allowed us to iterate super quickly from scratch on a new electron app. however, we faced difficulties ([as many developers do](https://medium.com/actualbudget/the-horror-of-blocking-electrons-main-process-351bf11a763c)) when putting some load on the main thread via IPC, as the renderer thread regularly freezes.

there are several solutions to this, one being having a second `BrowserWindow` that's hidden and communicates with the first window via the main thread's IPC bus. something like this isn't supported in nextron right now, or is it?

having a second next.js process building a worker process could be beneficial for building apps that require medium-level computation, especially as 1) next.js is running/included as dependency anyway and 2) next.js wraps webpack conveniently.

cheers!

**Comment by saltyshiomix** [comment]
@falafeljan 

Sorry for late replying your kind issue.

Currently nextron does not support that. So I want to investigate it, could you create simple example app for me?

I want to surely support your needs :)

**Comment by falafeljan** [comment]
thanks! i'll create an example app soon to showcase the requirements :-)

**Comment by lacymorrow** [comment]
This is doable with the current state of Nextron:) 

Create a second, hidden window and manage communication between the two renderer processes via IPC in the main process.

Here's an example app with a basic demo: https://github.com/lacymorrow/nextron-worker-process

**Comment by falafeljan** [comment]
sorry for being late to reply—thanks @lacymorrow, that's a fantastic example and requires no additional tooling! however, i'm facing issues as we are using native modules in our background worker, and i suspect that there is an inconsistency between V8 versions of the electron background thread and the chromium window... :|

**Comment by lacymorrow** [comment]
I'm closing this since a reasonable solution has been posted, please create a new issue if you still have questions :)

**Comment by falafeljan** [comment]
sorry for the late follow-up! in the end, as you kind of said before, nextron already supports ways of achieving the requested feature.

we had requirements for accessing the Node.js API, so running another renderer thread was not an option. however, we just added a separate bundle to nextron's `nextron.config.js` configuration and forked another process in the node context—maybe our approach is of use for some:

```js
import path from 'path';
import { fork } from 'child_process';

export default function forkBackend() {
  const workerProcess = fork(path.join(__dirname, 'backend.js'));
  workerProcess.on('exit', (code) => {
    if (code !== 0 && code !== null) {
      throw new Error(
        `Backend thread unexpectedly exited with code ${code}.`
      );
    }
  });

  return workerProcess
}

**Comment by lacymorrow** [comment]
Thanks for posting @falafeljan!

This is a fantastic workaround to using IPC calls. Just curious, what Node modules did you require?

**Comment by falafeljan** [comment]
i should have mentioned that we actually _are_ using an IPC bus! in the main thread, we relay IPC events between the backend and the renderer process. there are other solutions for establishing a dedicated IPC channel without relaying, though: https://github.com/okdistribute/electron-rabbit

we require nodegit (https://www.nodegit.org/) and perform some in-memory parsing, this frequently caused our renderer thread to block...

**Comment by lacymorrow** [comment]
I wanted to post this for visibility on this topic, there's a good writeup and example repo that illustrates this concept pretty nicely (and highlights the benefits): 
Post (https://jlongster.com/secret-of-good-electron-apps)
Repo (https://github.com/jlongster/electron-with-server-example)
