### ISSUE TITLE
Add support for API routes to Material UI example

### ISSUE THREAD

**Issue by Asciant** [saltyshiomix/nextron#61]
As the title asks, I’m trying to add support for API routes into the Nextron with Material UI example, although I’m getting stuck on the ipcRenderer part, where the app tends to freeze after the initial paint.

Any assistance would be appreciated.

**Comment by lacymorrow** [comment]
@Asciant Please post a method to reproduce or link to an example app that demonstrates the issue so that we may better help you.

Is there any console output in the main or renderer processes?

**Comment by Asciant** [comment]
I don’t have a sample unfortunately, but this was what I did (steps below). I assume there is some caveat with the api routes and that I have missed some configured that is lacking between the api-routes example and the material UI example.

Method to reproduce:

1. Create a new project from the JavaScript Material UI example (nextron init my-app --example with-javascript-material-ui)
2. Add an api folder to the pages directory
3. Add a file to the api directory (export an arrow function and return 200 with a json message object - same as in the with api routes example
4. Attempt to communicate with the api route from the home page jsx file through electron (const ipcRenderer = electron.ipcRenderer).

The electron variable doesn’t seem to ever be accessible, and the app paints in electron but no elements are available in console and app isn’t able to be interacted with.

**Comment by lacymorrow** [comment]
@Asciant Most Electron modules load on _either_ the server or the browser, not both. Because of the nature of server-side-rendering, we have to check for existence of the `ipcRenderer` module before using it. Ex: https://github.com/saltyshiomix/nextron/blob/master/examples/ipc-communication/renderer/pages/home.jsx#L13

**Comment by Asciant** [comment]
Thanks Lacy, in the end I used IPC to achieve what I was going for.
