### ISSUE TITLE
next.js warning: The static directory has been deprecated in favor of the public directory. 

### ISSUE THREAD

**Issue by alexnitta** [saltyshiomix/nextron#63]
When running `yarn dev`, I see this warning in the console:
```
The static directory has been deprecated in favor of the public directory. https://err.sh/zeit/next.js/static-dir-deprecated
```

I think the fix may be as simple as updating the `static` file paths to use `public` instead.

**Comment by saltyshiomix** [comment]
Thanks @alexnitta ,

You may use old examples of nextron. Latest examples are renamed to `public` already :)

**Comment by alexnitta** [comment]
Ah, I see. Thank you!

**Comment by saltyshiomix** [comment]
@alexnitta You're welcome :)

If you have any troubles, feel free to open issues 👍
