### ISSUE TITLE
Access underlying `BrowserWindow` object

### ISSUE THREAD

**Issue by Southclaws** [saltyshiomix/nextron#67]
Hey, first of all thanks for such a great project!

Is there a way to access the underlying `BrowserWindow` object from a page? My use-case is to load a remote page into the window at some point. I could just use an iframe (or webview when stable).

Thanks.

**Comment by lacymorrow** [comment]
Hi @Southclaws,

To clarify, are you trying to reference the `BrowserWindow` from the renderer process?

My suggestion would be to add an IPC event listener to your background process that performs the behavior (loading a remote resource) and trigger this event from your renderer process.

**Comment by lacymorrow** [comment]
It's not recommended for security reasons but if you set 
```js
webPreferences: { nodeIntegration: true }
```

You can just use the remote module like: `const { BrowserWindow } = require('electron').remote`

The recommended way is to use a `preload.js` and the `ContextBridge`.
