### ISSUE TITLE
How to deploy with `now.sh`?

### ISSUE THREAD

**Issue by JerryGreen** [saltyshiomix/nextron#69]
How to properly deploy the application with [now.sh](https://now.sh)?

I mean, I want to have both types of application:

1. in an electron wrapper
2. and as a web service

My main concern is how to handle `renderer` path properly. Looks like I need some config like:

```jsonc
// now.json
{
  "version": 2,
  "builds": [{ "src": "renderer/package.json", "use": "@now/next" }]
}
```

But this brings a lot of mess with paths, requires a symlinked package.json, and I think maybe there's simpler way...

**Comment by JerryGreen** [comment]
I've found it's possible to pass a [nextron config](https://www.npmjs.com/package/nextron#nextronconfigjs), like:

```js
// nextron.config.js
module.exports = {
  rendererSrcDir: '.',
}
```

So since my NextJS code in my root now, it's as easy to deploy as before. Though, it'll require additional workaround in `package.json`:

```json
"now-build": "WEB=true next build",
```

And something like this:

```js
const { WEB } = process.env

const withElectron = previousNextConfig => ({
  ...previousNextConfig,
  webpack(previousWebpackConfig, options) {
    const webpackConfig = {
      ...previousWebpackConfig,
      target: WEB === 'true' ? undefined : 'electron-renderer',
    }
    return buildWebpackConfig(previousNextConfig, webpackConfig, options)
  },
})

module.exports = withElectron()
```

Still, much easier than mess with `renderer` folder.

**Comment by lacymorrow** [comment]
@saltyshiomix, this seems like it could be a common use-case, what would you think about building this in?

At the least it's probably worth documenting, thanks for doing the digging @JerryGreen 👍

**Comment by JerryGreen** [comment]
@lacymorrow yea, it wasn't very obvious of how to make it work in both web and electron. I have a pair of ideas of how to make this more friendly:

1. Use `rendererSrcDir: '.'` by default
2. Move `pages` to `src/pages`
3. Move `main` to `src/electron-main` (this may break things a bit)
4. Encapsulate my `withElectron` function into nextron, so I may:
`const { withElectron } = require('nextron')`
5. Add `"now-build": "WEB=true next build"` hint into this repo readme

Also, potential number 6: I'm not sure about `"postinstall": "electron-builder install-app-deps"`, - currently, it's executed inside Zeit Now deployments too because it has to, but this looks like a requirement for just electron, not the web. To make sure, I've tried to remove it, and the web version is still working with no problems. So it's probably a bad place for `postinstall`, and better to include it into nextron cli instead.

If anyone started a PR, I may probably help to settle it all down, if it's needed.

**Comment by k4mr4n** [comment]
@JerryGreen thank you, I followed these instructions to adopt the Nextron into my existing Nextjs application, and it's working fine on dev. after publishing the desktop app, the app is running fine but the links don't work anymore.

I'm getting:
```
Uncaught (in promise) Error: invariant: invalid relative URL
    at e.parseRelativeUrl (92eeeb1db25055bdd5a51a457eb86bdc3e790c7c.27875c4685628d0a95aa.js:1)
    at t.<anonymous> (92eeeb1db25055bdd5a51a457eb86bdc3e790c7c.27875c4685628d0a95aa.js:1)
    at s (92eeeb1db25055bdd5a51a457eb86bdc3e790c7c.27875c4685628d0a95aa.js:1)
    at Generator._invoke (92eeeb1db25055bdd5a51a457eb86bdc3e790c7c.27875c4685628d0a95aa.js:1)
    at Generator.next (92eeeb1db25055bdd5a51a457eb86bdc3e790c7c.27875c4685628d0a95aa.js:1)
    at r (92eeeb1db25055bdd5a51a457eb86bdc3e790c7c.27875c4685628d0a95aa.js:1)
```

I'm using a regular Next/Link component nothing fancy here.
I'll appreciate it if you guide me here?
Thanks.
cc: @lacymorrow

**Comment by k4mr4n** [comment]
I think my issue is a duplicate of this one here
https://github.com/saltyshiomix/nextron/issues/95
