### ISSUE TITLE
How to stop Electron app from restarting when saving changes to main process?

### ISSUE THREAD

**Issue by garyking** [saltyshiomix/nextron#75]
When I'm developing an Electron app with Nextron, and I make changes and save a file in the main process, then the Electron app restarts automatically. Is there any way to disable this feature? Maybe, temporarily? Such as an option to `nextron`?

Also, is it possible that when Electron is relaunched, to remain on the same URL that it was previously on?

**Comment by lacymorrow** [comment]
Hi @garyking, I've just created a PR to add the ability to run Nextron without watching and restarting.

Until I have time to test it and maybe get @saltyshiomix's input, you can grab an updated plugin file here: https://gist.github.com/lacymorrow/d843fa4087308799627dd8ee41dd0efb

Replace `node_modules/nextron/bin/nextron-dev.js` and run using `yarn dev --run-only` (or `npm run dev -- --run-only`

**Comment by saltyshiomix** [comment]
@garyking @lacymorrow 

I just published `nextron@^5.14.5`, which includes this solution.

Could you try it if you have time :)

**package.json**

```json
{
  "scripts": {
    "dev": "nextron --run-only"
  }
}
```
