### ISSUE TITLE
Trojan detected by Windows Security

### ISSUE THREAD

**Issue by danikaze** [saltyshiomix/nextron#79]
Threat detected: Trojan:Win32/Fuery.C!cl

file: APP_DIR\node_modules\.staging\app-builder-bin-a513e0cb\win\ia32\app-builder copy.exe

**Comment by danikaze** [comment]
Guess is not related to this project but this one... but still good to know I guess
https://github.com/develar/app-builder/issues/33

**Comment by lacymorrow** [comment]
Yes, unfortunately Nextron relies on this to build a distributable.

**Comment by jkoenig134** [comment]
I think the `app-builder copy.exe` will be deleted soon. The original `app-builder.exe` doesn´t cause problems.

**Comment by lacymorrow** [comment]
@jkoenig134 Is there a roadmap for these changes? I'd love to follow the development and update as soon as possible

**Comment by jkoenig134** [comment]
@lacymorrow it's not my project. It Was just a Suggestion. I hope the developer @develar will react on my issue soon.
