### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by muhajirdev** [saltyshiomix/nextron#8]
Hi @saltyshiomix ,
This is suuppeerrr.

May I know what's the roadmap for this project? Planned feature? etc.

Also this sentence `If you need performance with Electron, you should see these boilerplates` on README . Does that mean nextron is not performance enough?

**Comment by saltyshiomix** [comment]
Nextron is performant enough, but when production builds, electron-builder packages electron with **all node_modules**. This is not a performant.

So, `electron-builder` or `electron-packager` are needed tuning.

Nextron aims as simple as possible, so it use `electron-builder`'s recommended way 👍

**Comment by muhajirframe** [comment]
Ah, thanks for the clarification

**Comment by slater101** [comment]
Amazing project! Do you plan to keep working on this? 

I am surprised that more people have not noticed this already!

**Comment by saltyshiomix** [comment]
Thank you @slater101 !

I'm currently checking these:

- Any updates of npm packages and testing
- Looking for the way how to SPA with Next.js

Contributors and mainteners are welcome :)

**Comment by lacymorrow** [comment]
It's a year later, you've developed quite a fantastic application 🥇 

I'd like to know more about your goals for this project in the coming months and what your focus is. From the `readme`:

- Show a way of developing desktop apps using only web knowledge
- Be easy to use
- Be transparent and open to OSS developers

I think all apps should strive to be:
- Performant
- Well-documented
- Tested 😄

Github wants this to be:
- Easy to update
- Cross-platform

Do you have any interest in supporting web, or just desktop applications?

What's your stance on dependency updates? Always the latest and greatest versions of Next/React/Electron?

Lastly, what do you need help with?

**Comment by saltyshiomix** [comment]
@lacymorrow 

Thank you very much for your advices!
I'll reply it later today.

**Comment by saltyshiomix** [comment]
@lacymorrow 

First, sorry for late replying your kind advices and questions.

I'm not so familiar with English, and I wrote so long long reply, but I just pressed `cmd + w` omg...

**Comment by saltyshiomix** [comment]
I totally agree with you:

And my first thoughts of nextron goals are:

- make nextron **library**
  - nextron at first is a template generator, but currently nextron becomes like library
  - extract all examples to [create-nextron-app](https://npm.im/create-nextron-app)
  - deprecate and remove `nextron-init`
- documentation
  - follow semver or write version policies
  - fluent, MECE and dramatic (which I don't have!)
  - add testing
- examples
  - add simple testing
  - more examples like NEXT.js

All of these are what I want you to help!

I'm currently working on [react-ssr](https://github.com/saltyshiomix/react-ssr), so I can't have much time to maintenace nextron at least this month.

So I'm really grateful for you.

You make me drive to OSS!
