### ISSUE TITLE
Add support for css modules

### ISSUE THREAD

**Issue by codewaseem** [saltyshiomix/nextron#80]
How can we enable support for CSS modules?

**Comment by lacymorrow** [comment]
There are many different ways to include CSS in Next.js, CSS modules are
supported out of the box.

You can reference the Next.js docs for examples. I highly recommend the
Getting Started tutorial, here is the section describing CSS and using CSS
modules: https://nextjs.org/learn/basics/assets-metadata-css/css-styling

Let me know if you have any questions :)

**Comment by codewaseem** [comment]
Thanks for your response! But I updated the next.js to the latest version which has built-in support for CSS modules. Since this project is using custom CSS config (`next.config.js`), the built-in support for modules is getting dropped.

**Comment by Dea7h-cyber** [comment]
I suggest you try styled-components they are very good!

**Comment by lacymorrow** [comment]
@codewaseem Looks like Nextron may need to have another look to match the latest changes from Next.js. If you're okay with a third-party library, I can also recommend `styled-components`

**Comment by saltyshiomix** [comment]
@codewaseem 

Thank you for reporting the issue.
I'll investigate it soon :)

**Comment by colinhemphill** [comment]
After updating Next.js, you can just remove the `withCSS` wrapper in `next.config.js`. If you get complaints about how styles can only be imported into `_app`, just move your imports over there. When I ran the example Material UI project, all I had to do was move the `require('typeface-roboto')` into `_app.tsx`.

**Comment by amirmehdizadeh** [comment]
I'm using the with-javascript-ant-design example and I can't use CSS modules. any hope to fix this?

**Comment by saltyshiomix** [comment]
@amirmehdizadeh 

I tried hard but I got no any hope to use CSS modules with antd + next v11.

Available examples are here:

- [with-javascript-ant-design](https://github.com/saltyshiomix/nextron/tree/d0f13abfb688e22000aa43ec014f407a2fbe39a7/examples/with-javascript-ant-design)
- [with-typescript-ant-design](https://github.com/saltyshiomix/nextron/tree/d0f13abfb688e22000aa43ec014f407a2fbe39a7/examples/with-typescript-ant-design)

**Comment by saltyshiomix** [comment]
@codewaseem @amirmehdizadeh  CC: @lacymorrow @Dea7h-cyber 

Sorry for late reply.
Now we can use antd examples with css modules.
