### ISSUE TITLE
Error: ERR_FILE_NOT_FOUND (-6) loading 'app://./home.html'

### ISSUE THREAD

**Issue by codewaseem** [saltyshiomix/nextron#83]
Hi, Everything is working fine in development. But in production when I run the app I'm getting the following error.

```
UnhandledPromiseRejectionWarning: Error: ERR_FILE_NOT_FOUND (-6) loading 'app://./home.html'
```

**Comment by codewaseem** [comment]
This is related to #82, adding the following fixed the error. 
```
declare global {
    interface Window {
        require: any;
    }
}

```

**Comment by lacymorrow** [comment]
What URL are you loading the file from? It sounds like your filepath is not correct for a packaged environment. 

Can you try something like 
`await win.loadFile( path.join( __dirname, 'home.html' ) )`

**Comment by codewaseem** [comment]
@lacymorrow Thanks!

But that was not the problem. Actually the build was failing due to `window` is not defined error and the output didn't get generated. Hence the file was missing. Once I removed all the references to the `window` everything worked fine.

**Comment by lacymorrow** [comment]
Thanks for the explanation @codewaseem, cheers
