### ISSUE TITLE
A way to reduce production app size

### ISSUE THREAD

**Issue by Dea7h-cyber** [saltyshiomix/nextron#84]
Hi first of all great project! I love it! :) 🚀

Now to my question, is there a way to reduce the production (build) app size? Currently I have a pretty simple app but when I build it it's around ~170mb on Mac and probably around the same size on windows?!

I understand that electron is using chromium and needs to have it in the build to work, but is there any way to reduce the size somehow? Maybe turning some unnecessary feature off?

Thanks and have a great day! 🙏

**Comment by lacymorrow** [comment]
Unfortunately builds of >100mb are not uncommon with electron because of the reason you stated. You may be able to shave down your bundle by moving `dependencies` to `devDependencies` in your package.json but I can't offer anything more promising.
