### ISSUE TITLE
Getting electron-store settings in getInitialProps

### ISSUE THREAD

**Issue by sgtraptor** [saltyshiomix/nextron#86]
Hi,
it's more of a question than an issue probably. We use getInitialProps method for getting data via API request and deciding whether or not give access to this data based on user's saved token. If token is present and valid we return data in props and if not we put an error screen on display. We use electron-store for getting and saving user token which is working fine, but when we use ipcRenderer in getInitialProps it's undefined and therefore we can't get users token. Is there any way around this? I assume it's happening because of SSR? What is the most elegant way to handle this?

**Comment by lacymorrow** [comment]
@sgtraptor This is a great use-case and one I may want to build into an example.

As I understand it the app is probably running `next build` outside of the context of electron so `electron-store` is using a different config path. I would guess that you can output the `Store.path` to the console to verify it isn't corrent.

Do you have an example repo I can take a look at?

**Comment by sgtraptor** [comment]
We fixed some issues with this and I will try to create a simple project with this over the weekend. It is working now as should but I'm still not quite convinced if this is the best possible way.

**Comment by paragbaxi** [comment]
Also interested in this. Using getServerSideProps

**Comment by paragbaxi** [comment]
figured it out.

if you are receiving from main, use hooks and [ipcRenderer.invoke](https://github.com/sindresorhus/electron-store).

**renderer**

```
const Home = () => {
  const [people, setPeople] = useState([]);
  const classes = useStyles({});

  useEffect(() => {
    // componentDidMount()
    if (ipcRenderer) {
      const fn = async () => {
        people = await ipcRenderer.invoke(
          'getStoreValue',
          'people'
        );
        console.log('renderer:people', people);

        setPeople(people);
      };
      fn();
    }

    return () => {
      // componentWillUnmount()
    };
  }, []);

  return (
    <React.Fragment>
      <Head>
        <title>Next - Nextron</title>
      </Head>
      <div>
        {people}
      </div>
    </React.Fragment>
  );
};

export default Home
```

**main**

```
ipcMain.handle('getStoreValue', (event, key) => {
	return store.get(key);
});
```

**Comment by saltyshiomix** [comment]
@sgtraptor CC: @lacymorrow @paragbaxi 

Sorry for late reply.

We can't use sever process directly, because electron can handle only static files. So it's correct we use IPC stack!

Feel free to reopen the issue if you have any troubles :)
