### ISSUE TITLE
[Webpack problem] Failed to import 'main/*.ts' to renderer process

### ISSUE THREAD

**Issue by frothywater** [saltyshiomix/nextron#89]
I know that files under `main` folder and files under `renderer` folder are independently processed by two Webpack processes. Generally, there is no reason to import modules from main process to renderer process.

However... I find the IPC part of Electron too type-weak (simply using string literals for channel names), so I use [`electron-ipcfy`](https://github.com/vivimice/electron-ipcfy), which can provide a typed channel shared by any processes. (Trust me, that package is innocent. It just wraps `ipcMain` and `ipcRenderer` API. I wrote some similar stuff before and it failed too.)

Problem is, I create a shared channel in `main/api/FileService.ts`
```ts
export const fileService = ipcfy<FileService>('file');
```
...and import it in `renderer/pages/somePage.tsx`
```ts
import { fileService } from '../../main/api/FileService';
```
and it goes "**no loaders are configured to process this file**":
<img width="1018" alt="Screen Shot 2020-06-12 at 12 47 58 AM" src="https://user-images.githubusercontent.com/53869535/84416132-5f03e380-ac46-11ea-9812-3d9de568acd4.png">

It must be Webpack stuff... I'm not so good at that, and I think Webpack's configuration is sometimes too complex. (Yeah, I checked Nextron's config on Webpack and [that of Next.js](https://github.com/vercel/next.js/blob/canary/packages/next/build/webpack-config.ts) as well, with lots of frustration certainly. All after all, I just want a elegant best practice for cross-platform desktop app development... ☹️)

Maybe we can modify config on Webpack, but I'm unclear how to do so. Or do you have a better solution to the mentioned problem, without having to do such an unpleasant import? I'm glad to hear about it. And I'm also willing to make any contribution to this project! 😃

**Comment by luker2** [comment]
@saltyshiomix I get the same error trying to share `.ts` between `main` and `renderer`. I've created a `shared` folder at the root level. Any webpack example for allowing something like this?
