### ISSUE TITLE
getServerSideProps never called

### ISSUE THREAD

**Issue by eduardocp** [saltyshiomix/nextron#91]
Hey there! Thank you for all of your incredible and wonderful work.

I have several pages with `getServerSideProps` but it looks like they are never called on `.exe` generated by `yarn build`. What are the correct settings when you have `getServerSideProps`?

Thanks in advance!

**Comment by eduardocp** [comment]
Forget it, I saw the closed bugs related to the subject and changed my approach.

Thank you!

**Comment by iamchathu** [comment]
@eduardocp  can you link the related bug please?

**Comment by eduardocp** [comment]
> @eduardocp can you link the related bug please?

For sure, #57
